In [1]:
import pandas as pd

### Reading in CSVs
Creating Dataframes and a dictionary for use in the transformation

In [2]:
url_labor_force = '../Raw Files/Labor_Force_Participation_by_State/monthly.csv'
url_construction = '../Raw Files/Construction/monthly.csv'
url_education = '../Raw Files/Education/monthly.csv'
url_hospitality = '../Raw Files/Hospitality/monthly.csv'
url_manufacturing = '../Raw Files/Manufacturing/monthly.csv'

In [3]:
df_labor_force = pd.read_csv(url_labor_force, index_col=0)
df_construction = pd.read_csv(url_construction, index_col=0)
df_education = pd.read_csv(url_education, index_col=0)
df_hospitality = pd.read_csv(url_hospitality, index_col=0)
df_manufacturing = pd.read_csv(url_manufacturing, index_col=0)

In [4]:
dfs = {'us_labor_force':df_labor_force,
'us_construction':df_construction,
'us_education':df_education, 
'us_hospitality':df_hospitality, 
'us_manufacturing':df_manufacturing,}

In [5]:
#Checking Import
df_manufacturing

,AKMFG,ARMFG,AZMFG,CAMFG,COMFG,CTMFG,DEMFG,FLMFG,GAMFG,HIMFG,...,SMU11000003000000001SA,TNMFG,TXMFG,UTMFG,VAMFG,VTMFG,WAMFG,WIMFG,WVMFG,WYMFG
observation_date,,,,,,,,,,,,,,,,,,,,,
1990-01-01,12.4,218.4,177.3,1985.5,169.7,305.1,42.6,521.3,524.9,21.0,...,7.5,502.7,938.8,101.6,391.3,44.2,337.7,524.5,81.9,8.9
1990-02-01,12.4,218.9,177.6,1985.4,170.0,304.8,46.7,519.9,526.9,21.0,...,7.5,503.8,939.4,101.9,391.0,43.7,337.4,527.9,82.1,8.8
1990-03-01,12.9,217.8,177.1,1982.7,170.3,304.5,46.9,517.8,528.2,21.0,...,7.5,504.0,940.8,101.9,391.6,43.4,338.6,526.8,82.5,9.1
1990-04-01,13.7,219.0,176.5,1983.1,171.1,304.8,46.7,513.4,529.4,20.6,...,7.4,503.9,942.2,104.1,390.6,43.0,337.2,525.1,82.7,9.0
1990-05-01,14.5,219.2,176.7,1980.3,170.4,302.9,46.7,513.2,527.5,20.4,...,7.3,504.7,940.7,104.1,389.1,43.2,336.4,525.3,82.7,9.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-01,12.9,158.7,192.6,1214.4,146.3,151.5,26.4,425.8,425.6,13.0,...,1.0,353.3,981.0,154.3,233.3,27.3,269.6,455.7,45.0,10.4
2025-11-01,12.3,158.8,192.7,1212.2,145.5,151.8,26.2,424.2,424.3,13.0,...,1.0,352.8,980.1,153.6,232.8,27.3,267.9,454.8,44.9,10.4
2025-12-01,12.7,158.5,191.9,1213.1,145.4,151.2,26.5,424.9,427.0,13.0,...,1.0,352.0,981.1,154.3,232.3,27.4,269.7,454.6,45.0,10.4
2026-01-01,12.5,159.0,192.8,1214.3,144.3,152.2,26.3,428.7,425.7,13.1,...,1.0,351.9,977.0,154.4,230.2,27.5,271.0,451.6,44.9,10.4
2026-02-01,12.6,158.7,193.1,1211.9,143.7,152.6,26.4,428.5,425.5,13.1,...,1.0,351.9,979.5,153.6,228.6,27.4,271.1,451.5,44.9,10.3

### Creating Mapping between State Abbrivations and Names
Every CSV uses the same 2 letter abbrivation to identify the State

In [6]:
mapping = {'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'DS': 'Unknown / Not a U.S. state',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WY': 'Wyoming'}

### Indivual Cleaning for Manufacturing
The columns for Manufacturing in District of Columbia and Manufacturing in Alabama are given non-standard ID codes

In [7]:
manufacturing_mapping = {'SMS11000003000000001' : 'DC', 
                         'SMU01000003000000001SA' : 'AL'}
for name, df in dfs.items():
    if name == 'us_manufacturing':
        df.rename(columns=manufacturing_mapping, inplace=True)
        df.drop(columns='SMU11000003000000001SA', inplace=True)
    else:
        pass

### Bulk Transformations
Changing each csv's different column code of (State + Survey) into the State Name

In [8]:
for name, df in dfs.items():
    df.rename(columns=lambda x: x[:2], inplace=True)
    df.rename(columns=mapping, inplace=True)
    df.rename_axis(None,inplace=True)

### Individual Cleaning
Labor Force has one null State and no information for October 2025

Construction has no information for Tennessee

In [9]:
# df_labor_force cleaning
df_labor_force.drop('Unknown / Not a U.S. state', axis=1, inplace=True)
df_labor_force.drop('2025-10-01', axis=0, inplace=True)
#df_construction cleaning
df_construction.drop('Tennessee', axis=1, inplace=True)

### Transposing
Making it so that rows are states and columns are dates to align with Statistics Canada

In [13]:
dfs = {name: df.T for name, df in dfs.items()}

In [ ]:
#Final Checking
for name, df in dfs.items():
    print(name)
    display(df)

us_labor_force

,2015-01-01,2015-02-01,2015-03-01,2015-04-01,2015-05-01,2015-06-01,2015-07-01,2015-08-01,2015-09-01,2015-10-01,...,2025-04-01,2025-05-01,2025-06-01,2025-07-01,2025-08-01,2025-09-01,2025-11-01,2025-12-01,2026-01-01,2026-02-01
Alaska,362704.0,362522.0,362346.0,362180.0,361928.0,361540.0,361138.0,360803.0,360526.0,360364.0,...,364680.0,364733.0,364769.0,365105.0,365769.0,366639.0,367709.0,367671.0,368676.0,369379.0
Alabama,2166864.0,2169495.0,2171897.0,2173967.0,2174501.0,2173391.0,2171593.0,2170789.0,2170975.0,2173053.0,...,2377299.0,2375367.0,2374605.0,2375655.0,2378765.0,2383172.0,2387873.0,2387810.0,2387630.0,2386304.0
Arkansas,1331412.0,1332284.0,1333305.0,1334305.0,1334929.0,1334831.0,1334168.0,1333299.0,1332649.0,1332905.0,...,1429050.0,1430261.0,1431816.0,1434815.0,1438959.0,1443627.0,1448832.0,1448666.0,1451314.0,1454559.0
Arizona,3090768.0,3093823.0,3097355.0,3101717.0,3106411.0,3110554.0,3113926.0,3116760.0,3119596.0,3123660.0,...,3792200.0,3794357.0,3797619.0,3802368.0,3807590.0,3812476.0,3815687.0,3814917.0,3814212.0,3800676.0
California,18818212.0,18826972.0,18838028.0,18848322.0,18852828.0,18848420.0,18839426.0,18832394.0,18832610.0,18846578.0,...,19792412.0,19810355.0,19818339.0,19836296.0,19850185.0,19856618.0,19878800.0,19878043.0,19861662.0,19826577.0
Colorado,2807587.0,2808391.0,2809713.0,2811615.0,2813611.0,2815094.0,2816411.0,2818352.0,2821852.0,2827738.0,...,3265416.0,3261371.0,3258203.0,3255953.0,3254443.0,3253988.0,3254030.0,3254073.0,3248790.0,3238456.0
Connecticut,1912878.0,1912990.0,1912140.0,1910119.0,1907097.0,1903378.0,1899802.0,1897248.0,1895796.0,1895443.0,...,1940412.0,1938120.0,1935981.0,1934347.0,1933239.0,1933063.0,1933758.0,1933851.0,1931253.0,1929141.0
District of Columbia,379620.0,379593.0,379763.0,380227.0,380770.0,381214.0,381639.0,382112.0,382552.0,382995.0,...,414252.0,413222.0,411850.0,410461.0,409378.0,408743.0,408918.0,409140.0,407975.0,406902.0
Delaware,458015.0,458674.0,459436.0,460259.0,461075.0,461824.0,462553.0,463324.0,464181.0,465198.0,...,514928.0,515273.0,515621.0,516023.0,516415.0,516798.0,517116.0,517069.0,516219.0,514718.0
Florida,9547419.0,9552483.0,9560034.0,9569380.0,9578842.0,9586944.0,9594674.0,9603740.0,9615536.0,9632214.0,...,11112016.0,11097235.0,11082777.0,11076857.0,11080810.0,11093357.0,11116493.0,11117284.0,11123760.0,11141202.0
Georgia,4739013.0,4737111.0,4736589.0,4735953.0,4735356.0,4734169.0,4732561.0,4730889.0,4731195.0,4734979.0,...,5407544.0,5407664.0,5408413.0,5413580.0,5421660.0,5430828.0,5442066.0,5441402.0,5445643.0,5451101.0
Hawaii,680210.0,680652.0,681108.0,681613.0,682114.0,682503.0,682855.0,683337.0,684081.0,685238.0,...,687779.0,687381.0,686897.0,686826.0,687027.0,687361.0,688042.0,688037.0,688022.0,687830.0
Iowa,1708406.0,1707615.0,1707029.0,1706203.0,1704780.0,1702889.0,1701152.0,1700151.0,1700298.0,1702038.0,...,1736357.0,1736268.0,1735617.0,1735819.0,1737046.0,1739237.0,1743419.0,1743797.0,1743617.0,1741535.0
Idaho,789286.0,791359.0,793573.0,795780.0,797796.0,799382.0,800658.0,801819.0,802951.0,804326.0,...,1006555.0,1006605.0,1006770.0,1007286.0,1008027.0,1008929.0,1010002.0,1009937.0,1009819.0,1008136.0
Illinois,6530801.0,6531408.0,6536364.0,6544294.0,6551834.0,6556268.0,6558362.0,6560595.0,6565320.0,6575528.0,...,6610845.0,6595687.0,6580997.0,6568380.0,6559231.0,6555136.0,6557672.0,6559867.0,6560516.0,6570062.0
Indiana,3246591.0,3247085.0,3248870.0,3252300.0,3256839.0,3261547.0,3266590.0,3272212.0,3278980.0,3288343.0,...,3507483.0,3508068.0,3509583.0,3510853.0,3510718.0,3509507.0,3506474.0,3506135.0,3503591.0,3498263.0
Kansas,1497763.0,1497519.0,1497293.0,1497182.0,1497110.0,1496942.0,1496837.0,1497096.0,1497880.0,1499217.0,...,1567609.0,1569404.0,1571473.0,1574003.0,1576650.0,1579116.0,1581114.0,1580822.0,1579509.0,1578265.0
Kentucky,1987156.0,1985437.0,1983941.0,1982464.0,1980575.0,1978069.0,1975923.0,1975210.0,1976555.0,1980054.0,...,2113284.0,2113717.0,2114206.0,2115132.0,2116407.0,2118090.0,2120091.0,2119991.0,2114539.0,2108665.0
Louisiana,2169690.0,2167248.0,2164327.0,2160724.0,2156254.0,2150797.0,2144721.0,2138864.0,2134210.0,2131724.0,...,2087432.0,2086561.0,2085577.0,2087188.0,2091807.0,2098614.0,2108081.0,2108050.0,2112820.0,2117818.0
Massachusetts,3632559.0,3630125.0,3627911.0,3626445.0,3624724.0,3621649.0,3617532.0,3613335.0,3610168.0,3609632.0,...,3951418.0,3949636.0,3948218.0,3946177.0,3943000.0,3939694.0,3935591.0,3935586.0,3926744.0,3915271.0
Maryland,3157724.0,3160431.0,3163898.0,3167278.0,3169758.0,3170663.0,3170232.0,3169189.0,3168394.0,3168925.0,...,3233050.0,3234236.0,3233598.0,3233639.0,3231872.0,3227159.0,3222693.0,3221708.0,3214795.0,3211231.0
Maine,695333.0,694372.0,693273.0,692064.0,690812.0,689522.0,688316.0,687297.0,686620.0,686563.0,...,708568.0,708353.0,708146.0,708211.0,708528.0,709123.0,710100.0,710128.0,709117.0,708316.0
Michigan,4764774.0,4763075.0,4763675.0,4766275.0,4769372.0,4771847.0,4773803.0,4775840.0,4779395.0,4786771.0,...,5053176.0,5041830.0,5031033.0,5020617.0,5011265.0,5004120.0,4998918.0,4999837.0,4992846.0,4983743.0
Minnesota,3002256.0,3005497.0,3009713.0,3014026.0,3017178.0,3018332.0,3018015.0,3017335.0,3017390.0,3019206.0,...,3167062.0,3168185.0,3170280.0,3173356.0,3176798.0,3180407.0,3182913.0,3182266.0,3177776.0,3169201.0
Missouri,3046324.0,3048541.0,3050531.0,3051973.0,3052454.0,3051939.0,3051015.0,3050439.0,3050791.0,3052804.0,...,3161876.0,3162368.0,3162002.0,3163431.0,3166120.0,3169132.0,3175775.0,3175358.0,3177918.0,3177115.0
Mississippi,1249462.0,1252238.0,1255338.0,1257989.0,1259898.0,1260610.0,1260747.0,1260887.0,1262078.0,1264017.0,...,1295155.0,1294436.0,1294097.0,1294461.0,1294995.0,1295547.0,1296031.0,1295784.0,1293479.0,1292634.0
Montana,517396.0,518398.0,519291.0,519870.0,520065.0,520020.0,520051.0,520343.0,520872.0,521678.0,...,576503.0,576836.0,577151.0,577577.0,578036.0,578570.0,579266.0,579238.0,579463.0,578837.0
North Carolina,4680763.0,4686531.0,4693481.0,4700619.0,4706315.0,4709361.0,4710903.0,4712347.0,4714568.0,4719324.0,...,5289955.0,5289914.0,5290942.0,5294737.0,5300672.0,5308050.0,5317047.0,5316660.0,5313331.0,5311680.0
North Dakota,416126.0,415394.0,414498.0,413654.0,412965.0,412415.0,412068.0,411965.0,412104.0,412475.0,...,429401.0,429604.0,429864.0,430490.0,431457.0,432619.0,433994.0,433968.0,434885.0,435642.0
Nebraska,1013018.0,1012312.0,1012006.0,1012259.0,1012908.0,1013724.0,1014675.0,1015778.0,1017033.0,1018552.0,...,1095866.0,1097161.0,1098372.0,1099878.0,1101540.0,1103170.0,1104807.0,1104681.0,1104514.0,1104314.0
New Hampshire,750638.0,750753.0,750431.0,749781.0,748830.0,747698.0,746770.0,746324.0,746425.0,747110.0,...,774917.0,774909.0,774903.0,775092.0,775433.0,775952.0,776708.0,776712.0,777396.0,777213.0
New Jersey,4599138.0,4599819.0,4600965.0,4601645.0,4600754.0,4597878.0,4594206.0,4591020.0,4589208.0,4590617.0,...,4897988.0,4897944.0,4899596.0,4903658.0,4909106.0,4915086.0,4919896.0,4919038.0,4918046.0,4912673.0
New Mexico,940698.0,941207.0,941739.0,942216.0,942410.0,942102.0,941385.0,940443.0,939512.0,939028.0,...,986389.0,985461.0,984485.0,983892.0,983709.0,983988.0,985100.0,985342.0,985170.0,983967.0
Nevada,1389305.0,1390782.0,1392287.0,1393710.0,1394779.0,1395265.0,1395389.0,1395502.0,1395804.0,1396707.0,...,1660384.0,1661117.0,1662107.0,1665487.0,1671237.0,1678448.0,1687305.0,1687017.0,1694200.0,1698029.0
New York,9705061.0,9718246.0,9730674.0,9740242.0,9744552.0,9742165.0,9736639.0,9732451.0,9732729.0,9740366.0,...,9966421.0,9966598.0,9970634.0,9986380.0,10012631.0,10044581.0,10081101.0,10080281.0,10104607.0,10118757.0
Ohio,5737312.0,5731526.0,5728534.0,5727608.0,5726888.0,5724503.0,5720710.0,5717012.0,5715547.0,5719033.0,...,5961335.0,5954968.0,5947621.0,5941374.0,5936935.0,5935238.0,5936926.0,5937500.0,5932407.0,5929736.0
Oklahoma,1813648.0,1818867.0,1823690.0,1827272.0,1828834.0,1828173.0,1826170.0,1823735.0,1821679.0,1821067.0,...,2016136.0,2017934.0,2020199.0,2022048.0,2022719.0,2022471.0,2020442.0,2020051.0,2018658.0,2014158.0
Oregon,1958638.0,1959179.0,1961126.0,1964359.0,1968414.0,1972552.0,1976675.0,1980845.0,1985425.0,1991370.0,...,2211460.0,2213343.0,2215494.0,2217910.0,2219738.0,2221014.0,2221743.0,2221552.0,2218136.0,2214220.0
Pennsylvania,6444939.0,6448785.0,6454403.0,6461555.0,6468552.0,6473711.0,6477709.0,6481593.0,6486574.0,6494946.0,...,6523912.0,6521592.0,6521090.0,6526708.0,6537899.0,6552836.0,6571286.0,6570655.0,6582900.0,6587586.0
Rhode Island,566321.0,566771.0,567037.0,566925.0,566373.0,565447.0,564458.0,563629.0,562994.0,562667.0,...,594507.0,594412.0,594381.0,594146.0,593565.0,592799.0,591783.0,591788.0,590980.0,588904.0
South Carolina,2233242.0,2235851.0,2238395.0,2240573.0,2241910.0,2242091.0,2241576.0,2241066.0,2241281.0,2243185.0,...,2592395.0,2594540.0,2597055.0,2602867.0,2611841.0,2622603.0,2635089.0,2634542.0,2646468.0,2658086.0
South Dakota,449519.0,449491.0,449521.0,449658.0,449843.0,449968.0,450029.0,450086.0,450221.0,450545.0,...,490782.0,491216.0,491756.0,492428.0,493112.0,493705.0,494081.0,493994.0,493467.0,492816.0
Tennessee,3065281.0,3067489.0,3070631.0,3074122.0,3077173.0,3078968.0,3079697.0,3080105.0,3081151.0,3084457.0,...,3522012.0,3524620.0,3527455.0,3531436.0,3536188.0,3541397.0,3546463.0,3545878.0,3541853.0,3532590.0
Texas,13005030.0,12996949.0,12994457.0,12997813.0,13004689.0,13012436.0,13021327.0,13031358.0,13043523.0,13062295.0,...,15845628.0,15858126.0,15875182.0,15897795.0,15921704.0,15944844.0,15962121.0,15958627.0,15955231.0,15941826.0
Utah,1443189.0,1446330.0,1449776.0,1453518.0,1457187.0,1460409.0,1463234.0,1465935.0,1468803.0,1472335.0,...,1838168.0,1837840.0,1837615.0,1838332.0,1839933.0,1842268.0,1845293.0,1845208.0,1844105.0,1840984.0
Virginia,4237002.0,4234354.0,4232923.0,4232210.0,4231145.0,4228911.0,4226202.0,4223634.0,4221591.0,4221568.0,...,4535111.0,4529699.0,4524672.0,4520733.0,4517843.0,4516628.0,4518582.0,4519825.0,4518567.0,4513203.0
Vermont,353493.0,353453.0,353266.0,352923.0,352438.0,351857.0,351320.0,350907.0,350639.0,350573.0,...,350363.0,349680.0,349178.0,348673.0,348063.0,347408.0,346688.0,346776.0,345430.0,344047.0
Washington,3519204.0,3523168.0,3528031.0,3533695.0,3539458.0,3544400.0,3549209.0,3554823.0,3561553.0,3570132.0,...,4047911.0,4048701.0,4048655.0,4050631.0,4053622.0,4056992.0,4062809.0,4062730.0,4065082.0,4066446.0
Wisconsin,3093599.0,3092455.0,3091803.0,3091466.0,3091078.0,3090401.0,3090169.0,3091273.0,3094258.0,3099569.0,...,3122374.0,3115700.0,3108912.0,3104739.0,3104218.0,3107251.0,3115444.0,3116196.0,3121154.0,3126595.0
West Virginia,795082.0,794759.0,794694.0,794714.0,794426.0,793510.0,792080.0,790472.0,789089.0,788343.0,...,780258.0,779991.0,780168.0,780875.0,781869.0,782955.0,783871.0,783736.0,782645.0,782052.0
Wyoming,302001.0,301683.0,301424.0,301225.0,301027.0,300779.0,300513.0,300273.0,300090.0,300031.0,...,289328.0,288794.0,288285.0,287945.0,287825.0,287963.0,288447.0,288499.0,288454.0,288501.0

us_construction

,2015-01-01,2015-02-01,2015-03-01,2015-04-01,2015-05-01,2015-06-01,2015-07-01,2015-08-01,2015-09-01,2015-10-01,...,2025-05-01,2025-06-01,2025-07-01,2025-08-01,2025-09-01,2025-10-01,2025-11-01,2025-12-01,2026-01-01,2026-02-01
Alaska,18.2,18.2,18.5,18.3,17.9,17.7,17.5,17.4,17.0,17.2,...,19.0,18.9,18.9,18.7,18.7,18.9,18.8,18.4,18.9,18.6
Alabama,80.7,80.3,79.2,80.2,80.8,81.7,81.2,82.0,82.0,82.2,...,109.2,109.4,110.0,110.2,110.3,110.4,109.5,109.7,111.0,111.3
Arkansas,47.7,48.0,47.1,47.4,48.2,48.6,49.5,50.3,50.8,50.7,...,66.4,66.4,66.2,66.2,66.1,65.9,66.3,66.4,66.1,66.5
Arizona,124.2,124.3,124.6,125.2,125.9,125.8,126.3,126.9,127.3,128.1,...,225.2,224.3,223.8,223.3,222.6,221.7,221.8,222.7,223.2,223.8
California,706.5,708.2,712.8,718.2,723.7,727.9,734.7,740.8,741.1,753.2,...,901.0,896.6,894.1,893.1,888.6,880.8,885.9,880.8,885.4,884.5
Colorado,146.7,147.9,147.3,147.3,148.1,147.9,148.3,148.8,149.6,150.4,...,184.4,182.8,183.9,184.2,184.1,185.4,185.1,186.5,188.5,189.5
Connecticut,56.8,57.0,56.7,57.5,58.1,58.4,57.9,57.8,58.0,58.5,...,64.3,64.1,63.9,64.1,64.1,64.1,64.8,64.8,65.1,64.3
Florida,414.9,417.1,419.8,421.5,426.4,429.5,432.9,436.4,439.1,446.3,...,658.8,658.0,655.7,654.6,653.7,650.3,648.6,647.2,647.7,648.8
Georgia,166.1,167.0,165.8,167.9,168.9,169.9,170.1,170.6,171.0,171.8,...,235.7,234.8,235.7,236.8,236.7,237.1,236.4,236.2,236.2,232.5
Iowa,78.1,78.8,79.1,78.3,77.6,77.2,77.4,77.3,77.5,78.3,...,84.1,84.1,83.8,84.5,84.6,82.9,83.8,83.7,85.1,85.8
Idaho,37.5,37.9,38.4,37.8,38.0,37.9,38.0,38.1,37.8,38.5,...,74.7,74.6,75.2,75.0,75.3,76.1,77.1,77.7,74.7,75.4
Illinois,209.0,209.6,208.6,212.7,214.3,214.0,213.6,215.0,216.0,216.4,...,240.4,239.8,241.1,240.7,240.2,239.2,241.4,237.3,251.3,246.4
Indiana,125.6,125.9,125.0,125.1,127.0,126.3,126.7,127.8,128.0,128.6,...,175.2,175.1,175.1,177.4,177.3,176.4,176.5,174.2,175.4,174.6
Kansas,59.9,60.7,60.6,61.0,61.0,60.4,60.6,61.0,61.2,61.6,...,73.6,73.2,73.8,73.7,73.6,74.7,75.5,74.4,73.7,73.3
Kentucky,75.3,75.5,73.2,74.3,75.1,75.5,75.8,76.3,76.3,76.6,...,93.0,92.6,92.4,92.4,92.8,92.5,92.5,92.9,92.9,92.3
Louisiana,140.5,139.6,138.7,138.3,138.2,138.3,140.0,141.6,141.6,142.7,...,136.8,136.5,135.6,135.7,135.4,135.8,139.0,140.1,142.7,143.2
Massachusetts,133.7,133.5,133.6,135.9,139.1,139.6,140.0,140.9,141.3,142.6,...,166.9,166.4,166.0,165.6,165.7,163.5,165.0,165.2,165.8,166.0
Maine,26.1,26.0,25.9,25.8,26.6,26.7,26.9,26.9,26.8,27.0,...,35.6,35.5,35.6,35.6,35.5,35.6,35.8,36.0,36.5,36.8
Michigan,145.7,146.0,146.5,147.0,148.2,149.0,148.2,148.2,148.7,149.7,...,202.1,201.7,202.5,203.2,203.2,203.1,201.7,199.5,198.8,198.3
Minnesota,111.8,112.6,113.4,115.0,115.4,116.0,116.6,116.6,116.1,116.3,...,142.7,141.5,141.5,141.5,142.2,144.6,148.7,142.7,146.0,144.3
Missouri,112.3,114.0,112.4,112.5,113.7,113.4,114.0,114.8,115.1,116.4,...,149.8,150.0,151.1,151.7,151.9,152.2,154.7,154.9,160.1,155.9
Mississippi,46.7,47.0,46.0,46.4,46.1,45.5,45.9,46.0,46.0,45.8,...,53.7,53.6,53.7,53.9,53.7,54.4,54.6,53.9,53.0,53.3
Montana,26.1,26.6,26.6,26.1,26.2,26.1,26.5,26.5,26.5,26.6,...,37.3,37.3,37.2,37.1,37.1,37.5,36.8,36.9,37.8,38.3
North Carolina,184.0,185.9,184.8,186.0,188.7,189.0,189.9,191.1,191.8,192.3,...,278.1,278.7,279.4,279.8,279.9,281.0,282.7,283.6,286.1,286.7
North Dakota,37.5,36.9,36.4,35.3,35.2,34.4,33.8,33.6,33.3,33.2,...,30.5,30.5,30.5,30.7,30.9,30.1,30.9,30.7,31.0,30.6
New Hampshire,23.7,23.6,23.4,23.3,24.2,24.2,24.4,24.6,25.0,25.1,...,32.4,32.4,32.5,32.5,32.5,32.6,32.4,32.6,32.6,32.5
New Jersey,144.3,145.0,143.8,146.8,148.5,149.2,149.6,149.8,149.3,150.9,...,165.6,165.8,166.2,166.1,166.1,166.7,166.2,166.2,168.0,162.1
New Mexico,43.4,43.3,43.1,43.3,43.5,43.6,43.5,43.4,43.7,43.5,...,55.5,55.5,55.6,55.0,55.0,53.9,53.4,53.9,54.0,53.9
Nevada,66.9,67.4,67.5,67.9,68.7,69.4,70.1,71.1,71.3,73.1,...,111.5,111.7,113.3,113.2,113.1,114.4,113.1,110.7,114.2,115.2
New York,351.6,348.8,352.3,356.4,360.8,363.5,363.1,364.6,365.5,368.5,...,387.0,386.4,386.0,386.3,385.9,385.0,385.6,387.4,389.9,384.6
Ohio,197.4,197.5,196.1,198.1,199.9,199.1,200.2,201.3,201.9,203.6,...,258.7,258.8,259.5,260.4,260.5,258.5,260.6,262.2,261.6,262.6
Oklahoma,77.0,78.4,77.5,77.1,76.6,77.3,78.1,77.5,77.7,77.9,...,89.7,89.9,89.6,89.7,89.7,90.8,90.5,89.9,90.8,91.2
Oregon,81.2,82.0,82.2,81.5,81.8,82.4,82.7,83.4,84.2,85.5,...,113.4,113.1,112.6,112.3,111.6,112.8,113.0,110.6,111.4,111.7
Pennsylvania,231.0,230.8,227.4,232.3,234.9,236.2,235.6,238.4,239.2,238.8,...,263.4,263.3,263.6,264.1,264.3,263.7,265.3,263.0,266.0,263.0
Rhode Island,16.6,16.4,16.4,16.7,16.9,16.9,17.1,17.1,17.2,17.4,...,22.5,22.4,22.4,22.7,22.5,22.7,22.7,23.2,22.8,22.5
South Carolina,87.0,87.6,87.9,87.9,88.6,89.3,89.3,89.7,90.4,91.3,...,123.5,124.1,123.4,124.1,124.7,123.9,124.5,125.2,126.0,125.8
South Dakota,21.7,22.0,22.4,22.4,22.3,22.2,22.4,22.2,22.0,22.1,...,29.9,29.8,29.7,29.7,29.6,30.2,29.0,29.3,29.8,29.8
SM,150.1,150.6,150.4,152.1,153.3,153.5,154.5,155.5,156.1,158.5,...,164.3,164.6,164.3,164.7,164.9,165.4,167.1,166.8,169.1,165.0
SM,47.6,48.2,48.5,48.7,48.9,48.8,49.1,49.2,49.4,49.6,...,64.0,64.2,64.2,64.3,64.1,64.9,64.8,64.6,65.0,65.4
SM,110.8,111.2,109.3,111.5,112.4,112.7,113.6,113.3,114.3,116.0,...,165.3,165.3,165.6,166.5,166.7,166.7,167.2,166.1,165.3,164.9
Texas,676.2,678.8,676.7,672.4,678.4,682.5,685.5,689.1,688.5,690.7,...,902.0,902.5,904.2,907.5,906.6,903.6,905.5,903.4,913.9,912.9
Utah,82.2,82.8,83.0,83.0,83.5,84.3,84.9,85.7,86.6,87.5,...,143.0,142.6,142.1,141.7,141.9,141.8,141.9,142.0,142.0,142.4
Virginia,180.5,181.0,179.9,183.1,185.3,185.1,186.1,186.7,186.5,187.2,...,229.8,231.2,230.6,231.6,231.7,227.0,226.7,226.8,227.5,226.0
Vermont,15.0,15.0,15.0,15.0,15.3,15.2,15.1,15.2,15.2,15.2,...,16.3,16.3,16.3,16.4,16.4,16.0,16.1,16.2,16.8,16.4
Washington,169.5,170.7,171.4,172.0,173.0,173.5,173.5,173.5,173.7,174.9,...,220.2,219.1,218.1,217.2,217.2,216.5,214.4,214.9,218.2,217.2
Wisconsin,107.6,107.5,107.4,108.6,109.9,109.5,109.8,109.7,109.8,110.2,...,145.7,146.0,146.4,147.0,146.8,147.6,148.3,150.4,152.9,153.7
West Virginia,33.2,33.3,33.0,33.1,34.0,33.0,32.4,32.2,31.3,30.9,...,35.6,35.0,35.0,35.3,35.4,35.5,35.6,35.5,37.6,36.7
Wyoming,23.7,23.7,23.7,23.8,23.3,23.0,23.2,23.3,23.3,23.1,...,23.6,23.4,22.7,22.4,22.5,23.1,23.4,23.4,23.7,23.9

us_education

,2015-01-01,2015-02-01,2015-03-01,2015-04-01,2015-05-01,2015-06-01,2015-07-01,2015-08-01,2015-09-01,2015-10-01,...,2025-05-01,2025-06-01,2025-07-01,2025-08-01,2025-09-01,2025-10-01,2025-11-01,2025-12-01,2026-01-01,2026-02-01
Alaska,47.8,47.8,47.8,47.0,47.1,47.3,47.4,47.3,47.3,47.5,...,54.5,54.6,54.4,54.3,54.3,54.1,54.1,54.0,53.9,53.9
Alabama,231.3,231.6,230.5,232.1,232.5,232.7,233.1,234.0,233.9,234.5,...,264.2,263.2,264.3,264.5,264.3,263.1,263.7,263.7,265.1,265.8
Arkansas,173.2,173.3,173.3,173.6,174.1,174.8,175.5,176.0,176.3,176.6,...,209.9,209.8,210.8,210.8,210.7,210.7,210.9,211.8,212.2,212.4
Arizona,392.5,394.5,395.8,396.9,399.2,400.2,401.7,403.7,403.0,406.1,...,550.2,547.8,550.4,551.2,550.6,551.1,552.1,553.6,558.2,560.4
California,2420.6,2425.8,2431.9,2443.9,2451.3,2456.4,2478.0,2479.8,2485.2,2493.1,...,3459.6,3463.7,3482.4,3503.6,3518.3,3530.6,3543.9,3547.8,3576.5,3552.4
Colorado,306.3,307.5,308.6,310.1,311.4,313.0,314.0,314.9,315.7,318.0,...,395.9,392.5,398.8,400.8,401.7,400.6,402.1,402.3,406.7,405.7
Connecticut,334.2,333.3,332.9,333.3,333.6,335.1,334.9,335.1,334.2,335.3,...,376.8,376.0,376.2,376.2,376.5,377.3,379.5,379.8,380.3,380.7
Delaware,73.9,74.1,74.1,74.8,75.1,75.6,75.4,75.4,75.6,75.7,...,92.4,92.3,92.1,92.5,92.0,92.5,92.4,92.9,93.5,94.0
Florida,1174.1,1177.0,1180.6,1182.5,1187.7,1191.3,1193.4,1195.2,1200.3,1207.5,...,1591.9,1588.8,1592.9,1596.3,1596.9,1598.9,1608.9,1614.9,1618.2,1616.8
Georgia,534.9,535.8,537.3,537.0,539.4,542.1,543.3,545.8,547.7,552.3,...,725.7,723.2,729.0,731.7,732.0,733.5,736.3,738.5,740.8,742.8
Hawaii,82.7,83.4,83.3,83.3,83.8,84.1,84.0,84.2,84.2,84.9,...,91.0,90.8,91.5,91.3,91.5,92.1,92.1,92.1,92.7,92.5
Iowa,223.4,223.1,223.7,224.2,224.9,226.2,227.2,227.8,227.4,227.0,...,243.0,243.4,243.9,244.1,243.6,245.8,246.8,247.1,246.2,244.8
Idaho,94.5,94.7,95.1,95.8,95.9,96.5,96.7,96.7,97.4,97.6,...,142.7,143.2,143.5,143.7,144.0,141.0,141.8,143.0,143.1,143.2
Illinois,891.2,890.5,891.8,896.6,900.6,901.3,904.3,903.4,903.8,906.0,...,1023.9,1023.0,1029.6,1027.1,1027.0,1034.7,1035.2,1037.9,1032.4,1031.1
Indiana,442.2,443.1,444.6,445.8,446.0,446.8,449.3,450.9,447.5,451.9,...,521.5,521.9,523.2,522.5,520.4,520.9,521.0,522.3,524.6,527.4
Kansas,193.3,193.9,194.0,195.1,195.0,194.8,195.3,195.6,195.1,195.4,...,217.9,217.7,218.9,218.7,218.9,219.5,219.1,218.8,219.3,218.5
Kentucky,261.9,261.5,262.1,263.0,263.2,263.3,263.6,264.0,264.7,266.0,...,319.8,319.8,319.3,320.0,318.3,317.9,318.0,319.7,321.1,322.4
Louisiana,301.7,302.1,302.4,303.1,303.7,304.1,304.6,304.8,305.3,306.2,...,351.5,351.5,351.8,351.6,352.6,351.4,352.1,352.7,353.1,352.9
Massachusetts,746.2,746.4,749.0,751.1,755.0,756.7,758.0,758.6,760.0,762.4,...,848.8,848.1,851.2,848.4,846.7,849.6,850.2,851.2,853.9,850.5
Maryland,434.7,435.7,435.8,438.3,440.2,440.0,440.0,440.9,441.0,443.0,...,500.4,501.2,502.5,503.6,502.4,499.2,500.0,501.3,505.4,504.8
Maine,122.3,122.3,122.6,122.9,122.9,123.4,123.6,123.9,123.6,123.4,...,137.9,137.8,137.9,137.9,138.2,136.9,138.2,137.3,138.1,137.6
Michigan,649.1,649.1,650.4,648.7,651.0,652.2,652.9,656.1,653.9,660.1,...,732.2,733.8,735.3,735.9,734.6,734.4,734.8,736.7,737.9,737.9
Minnesota,500.1,502.4,504.0,502.8,504.5,505.3,506.6,507.9,509.5,510.8,...,608.4,609.1,611.4,613.9,614.0,614.1,616.3,616.5,621.2,625.3
Missouri,459.9,459.4,458.7,461.8,462.4,462.7,464.0,464.4,463.9,465.6,...,538.7,541.1,539.9,539.1,538.5,540.5,540.6,542.5,545.6,540.7
Montana,70.8,70.9,71.1,71.9,71.9,72.1,72.2,72.5,72.6,73.0,...,86.9,87.1,87.2,87.2,86.9,86.4,86.4,86.6,87.0,87.1
North Carolina,569.4,570.5,569.5,569.3,571.0,571.9,571.6,570.7,574.0,576.2,...,723.0,723.9,727.0,730.8,729.5,728.8,730.2,731.8,736.1,738.8
North Dakota,62.4,62.6,62.5,62.6,62.8,62.7,62.8,63.2,63.2,63.1,...,71.7,71.8,71.8,71.8,71.8,72.9,72.2,72.5,72.7,73.1
Nebraska,148.9,148.6,148.4,148.8,148.8,149.0,150.1,150.2,150.6,150.9,...,172.9,173.0,173.3,173.4,173.3,174.1,174.4,173.4,175.3,175.1
New Hampshire,114.9,114.6,115.0,115.0,115.5,115.6,115.8,115.7,115.4,116.1,...,129.7,130.7,130.9,130.9,130.7,130.5,130.0,130.3,129.7,130.5
New Jersey,640.6,641.4,643.1,642.6,644.3,646.2,647.4,648.0,647.4,649.5,...,799.4,799.3,799.6,801.4,802.5,811.5,815.7,817.1,818.8,820.0
New Mexico,129.2,129.5,130.1,130.7,131.5,132.3,132.3,132.6,133.1,134.2,...,152.4,152.7,153.0,153.8,153.8,152.3,154.1,153.7,154.3,155.0
Nevada,117.9,118.2,118.8,119.3,119.8,120.5,121.3,121.9,122.3,123.2,...,179.3,179.0,181.6,182.3,181.9,183.8,183.0,184.5,184.6,184.7
New York,1869.0,1870.8,1874.9,1877.8,1884.6,1889.9,1899.6,1899.6,1894.9,1909.4,...,2409.8,2421.4,2395.2,2402.1,2410.1,2414.4,2421.8,2433.3,2441.9,2447.1
Ohio,889.4,890.0,890.3,893.5,896.2,896.5,899.4,899.7,900.5,901.4,...,990.1,992.1,995.3,996.0,994.8,990.8,995.3,994.3,998.9,998.1
Oklahoma,229.5,229.7,229.8,230.4,230.8,231.4,231.8,232.6,232.9,233.1,...,281.0,279.2,278.6,278.9,279.6,278.9,279.5,280.6,281.8,282.9
Oregon,258.2,259.8,260.0,261.6,262.7,264.1,264.4,265.5,266.3,268.4,...,349.5,349.8,349.8,351.5,350.2,350.3,351.6,352.9,355.5,354.4
Pennsylvania,1187.0,1186.1,1185.5,1188.5,1190.3,1191.2,1191.6,1192.8,1193.3,1197.6,...,1385.2,1392.3,1393.5,1399.0,1397.8,1401.7,1403.0,1409.2,1418.8,1412.9
Rhode Island,105.8,105.1,105.3,105.4,105.1,106.1,106.1,105.7,105.9,106.0,...,116.3,115.0,113.4,113.8,114.1,114.8,114.6,115.2,115.9,116.1
South Carolina,232.8,233.5,234.1,234.6,235.7,236.5,236.9,237.5,237.9,238.4,...,315.3,313.8,314.0,316.2,317.0,318.8,319.6,320.3,320.8,320.5
South Dakota,68.2,68.4,68.6,68.7,68.7,68.9,68.5,68.7,69.0,69.2,...,80.2,80.2,80.6,80.3,80.3,80.3,80.5,81.5,81.2,80.8
Texas,1550.9,1556.0,1559.7,1567.6,1574.0,1575.7,1579.7,1584.7,1586.9,1591.2,...,1980.2,1969.4,1978.9,1984.1,1985.7,1990.3,1995.6,2001.6,2009.0,2002.9
Utah,178.8,179.3,180.0,179.3,181.2,182.3,182.5,183.5,184.8,185.7,...,250.7,250.3,253.0,253.9,251.6,251.1,251.2,252.0,253.3,253.9
Virginia,503.7,504.6,504.2,509.5,511.1,512.9,515.7,517.3,518.8,520.5,...,624.0,626.4,623.6,625.2,624.6,626.8,627.6,624.9,631.6,628.8
Vermont,63.3,63.1,63.2,62.9,63.9,63.7,63.7,63.7,63.7,63.8,...,64.4,65.1,65.1,65.4,65.0,65.4,65.6,65.3,65.8,65.9
Washington,445.5,445.1,445.4,446.1,446.7,450.0,448.7,448.7,449.9,450.9,...,564.5,565.8,565.7,564.4,564.9,568.2,570.7,573.3,572.4,570.1
Wisconsin,432.9,433.9,434.9,435.0,436.1,435.9,436.8,436.8,436.8,438.7,...,496.6,496.9,496.7,497.9,496.6,498.2,497.9,500.0,502.8,501.1
West Virginia,125.7,125.5,125.4,125.7,125.8,124.9,124.5,124.7,125.3,126.4,...,144.6,144.7,144.9,145.4,145.4,146.0,146.3,146.2,146.4,147.2

us_hospitality

,2015-01-01,2015-02-01,2015-03-01,2015-04-01,2015-05-01,2015-06-01,2015-07-01,2015-08-01,2015-09-01,2015-10-01,...,2025-05-01,2025-06-01,2025-07-01,2025-08-01,2025-09-01,2025-10-01,2025-11-01,2025-12-01,2026-01-01,2026-02-01
Alaska,34.9,35.0,35.0,34.9,35.5,35.0,34.9,34.9,35.3,35.1,...,36.4,36.2,36.4,36.3,36.1,36.4,36.3,36.6,36.6,36.3
Alabama,186.9,188.1,187.8,188.3,189.3,189.6,190.4,190.7,191.9,192.8,...,213.8,213.8,213.0,213.7,214.4,216.0,216.8,217.3,217.2,217.8
Arkansas,109.4,110.2,109.2,109.8,111.3,111.4,111.9,112.3,113.3,113.6,...,131.7,131.9,132.0,132.0,132.4,132.7,133.6,134.6,134.6,135.1
Arizona,295.9,295.2,296.2,297.3,297.7,298.5,299.1,300.2,300.2,301.9,...,369.3,367.2,368.9,369.0,368.5,365.9,366.1,366.0,367.0,371.0
California,1792.2,1799.9,1806.2,1809.3,1818.4,1822.6,1831.8,1839.1,1846.4,1854.2,...,2019.8,2017.7,2011.9,2015.6,2012.3,2022.6,2028.5,2031.2,2053.2,2048.5
Colorado,306.4,308.6,309.0,310.4,312.3,312.6,313.4,314.4,316.5,316.5,...,351.6,344.2,348.1,349.8,350.8,353.9,353.3,351.1,348.4,347.8
Connecticut,150.9,150.5,150.7,151.2,152.0,151.4,150.9,150.3,151.3,151.8,...,157.2,156.1,156.1,156.1,156.5,156.1,156.3,155.9,155.7,155.2
District of Columbia,73.8,72.8,72.6,71.8,72.5,72.8,73.1,73.7,73.3,73.0,...,77.4,77.0,75.9,75.7,75.1,76.0,76.4,75.3,75.1,75.0
Delaware,47.8,47.9,47.9,47.9,49.1,48.7,49.0,49.1,49.2,48.7,...,53.2,52.5,52.6,52.5,52.0,51.5,51.5,51.7,51.4,51.6
Florida,1111.5,1116.0,1119.9,1121.1,1125.3,1131.4,1135.0,1139.9,1145.2,1152.5,...,1333.0,1331.7,1330.9,1330.1,1328.5,1325.5,1326.5,1327.7,1327.6,1323.6
Georgia,438.9,442.1,442.2,443.1,444.9,447.4,448.0,450.1,453.9,454.7,...,520.6,518.5,519.5,519.5,518.6,517.1,518.5,516.3,517.4,516.4
Hawaii,117.3,117.2,117.1,117.3,117.9,117.8,118.4,118.9,119.0,119.4,...,120.7,120.0,120.2,120.5,120.4,122.2,121.2,120.9,121.4,121.5
Iowa,139.4,139.8,140.0,139.4,140.6,140.8,141.0,141.2,141.5,141.7,...,145.4,144.9,143.7,143.5,142.4,139.9,140.0,138.5,138.6,139.2
Idaho,67.0,66.9,67.5,67.0,67.9,68.0,68.6,68.8,69.5,69.6,...,94.7,94.7,95.0,95.1,94.8,92.2,92.2,91.5,92.5,91.7
Illinois,565.2,568.6,568.9,572.8,577.8,579.0,579.8,581.1,584.0,586.6,...,606.4,604.0,605.5,605.9,603.7,605.1,602.5,603.4,602.7,601.6
Indiana,298.0,298.3,298.3,298.8,300.1,301.0,300.9,301.4,302.3,302.6,...,314.5,314.6,315.1,313.8,312.8,307.2,307.9,304.3,303.3,303.7
Kansas,125.3,125.7,125.2,124.9,124.8,125.7,126.0,126.2,126.4,126.8,...,133.9,132.5,133.8,133.8,134.1,132.9,133.6,132.8,132.8,133.6
Kentucky,185.8,185.9,184.1,185.8,187.0,187.4,188.0,188.1,189.3,189.8,...,206.4,206.6,206.4,206.7,206.2,206.9,207.0,207.4,206.2,206.9
Louisiana,226.0,226.8,226.6,226.4,227.0,227.4,228.5,228.6,229.4,230.5,...,225.4,223.5,225.1,225.4,223.7,226.0,225.6,225.6,224.9,225.1
Massachusetts,348.3,345.5,346.9,346.2,353.9,349.4,350.7,351.7,351.8,352.7,...,366.9,361.3,364.1,362.5,363.3,368.0,365.7,369.4,370.1,368.3
Maryland,264.5,265.2,263.2,265.1,268.6,267.2,268.5,268.8,268.9,268.9,...,272.5,268.8,268.0,268.3,268.2,265.7,266.6,268.6,270.7,269.9
Maine,64.0,63.6,63.9,64.0,64.9,64.2,64.5,64.6,64.9,65.2,...,71.3,70.3,70.6,70.2,71.2,70.7,71.7,72.0,71.7,71.8
Michigan,410.4,410.3,410.7,408.6,413.7,412.7,414.8,414.7,417.8,417.4,...,433.6,431.9,431.2,430.8,428.8,426.5,425.6,425.4,424.5,423.1
Minnesota,255.8,256.4,256.9,257.5,259.5,259.9,259.7,259.8,261.1,262.3,...,274.8,273.1,272.6,273.6,272.5,272.9,272.5,271.6,268.8,266.8
Missouri,289.7,290.8,289.3,289.8,292.6,292.2,293.2,293.4,295.3,295.3,...,310.7,308.1,309.3,309.4,307.3,309.7,309.0,306.6,312.3,312.9
Mississippi,126.8,127.4,127.0,128.1,128.6,128.7,129.3,129.4,129.9,130.8,...,135.5,135.2,135.6,135.7,134.7,135.6,137.8,136.4,135.6,135.4
Montana,61.4,61.8,62.0,62.0,62.5,62.2,62.5,62.8,63.2,63.5,...,73.6,73.5,74.3,74.1,74.0,74.7,73.8,73.9,74.0,73.5
North Carolina,453.4,455.1,454.2,454.0,457.2,459.7,461.1,461.9,464.7,465.8,...,543.5,541.4,541.9,541.2,542.4,542.9,546.0,547.7,548.0,546.1
North Dakota,41.0,41.0,40.9,40.9,41.1,40.9,40.6,40.6,40.7,40.5,...,41.1,41.3,40.9,40.8,41.0,40.8,40.6,39.6,40.0,40.0
Nebraska,87.5,87.9,88.1,87.2,88.0,88.3,88.5,88.6,89.5,89.1,...,101.8,101.6,101.5,102.1,101.3,100.6,100.8,101.1,100.0,99.8
New Hampshire,67.8,67.4,68.1,68.0,69.3,68.5,68.8,68.7,69.0,69.0,...,77.2,77.2,77.1,76.9,76.7,77.4,76.3,75.5,75.8,76.1
New Jersey,355.1,356.0,355.0,355.5,359.8,356.6,360.0,360.5,363.1,363.1,...,415.0,408.1,408.7,408.3,407.1,408.9,407.4,408.2,406.0,407.8
New Mexico,92.0,92.2,92.5,92.8,92.9,92.9,93.1,93.0,93.3,93.7,...,99.2,99.0,99.1,99.3,99.0,100.3,101.5,99.0,97.2,99.2
Nevada,339.9,340.5,340.5,340.1,340.3,340.2,340.4,340.6,341.3,342.8,...,360.9,357.5,361.9,363.9,361.7,359.1,361.7,364.0,363.9,365.5
New York,889.0,889.8,891.9,893.5,903.2,898.1,902.8,904.2,909.4,908.9,...,936.0,926.6,931.5,933.8,932.0,931.2,935.7,933.1,932.2,929.0
Ohio,532.0,532.9,533.3,535.0,538.7,538.4,539.5,541.2,545.4,543.4,...,570.6,567.7,567.9,570.6,569.8,569.6,569.5,568.5,570.2,569.0
Oklahoma,158.7,159.4,158.6,160.1,161.3,162.8,162.9,163.3,163.0,163.8,...,185.6,183.5,183.2,182.5,182.1,183.0,181.7,181.0,180.4,180.6
Oregon,187.4,188.6,189.0,189.2,190.4,191.1,192.1,192.8,193.5,194.2,...,207.9,207.8,207.3,206.8,205.7,205.7,208.1,208.0,209.2,207.7
Pennsylvania,540.5,541.1,539.3,541.5,545.1,545.0,545.6,546.5,550.1,549.8,...,574.9,571.9,570.8,572.5,572.5,573.8,574.7,572.6,576.7,574.9
Rhode Island,56.3,55.0,55.4,55.8,57.0,55.9,56.3,56.3,56.8,56.7,...,61.8,61.1,61.5,61.5,61.4,62.0,61.6,62.3,62.5,61.5
South Carolina,235.0,236.3,236.4,236.6,236.9,237.5,238.8,239.3,239.5,241.3,...,282.8,282.9,281.7,281.0,280.9,286.2,286.3,288.2,288.7,285.7
South Dakota,45.6,45.9,45.9,45.7,46.1,46.0,46.2,46.2,46.4,46.3,...,51.4,50.7,50.7,50.7,50.6,52.8,53.2,54.2,54.1,54.4
Tennessee,302.1,303.1,301.7,305.4,308.2,308.4,308.4,309.4,310.9,311.9,...,368.3,365.8,366.8,367.0,366.4,368.5,368.1,368.2,370.4,368.2
Texas,1211.5,1219.0,1220.2,1227.9,1235.2,1240.5,1246.8,1251.2,1257.9,1262.0,...,1533.4,1528.6,1527.8,1527.4,1530.5,1532.1,1531.0,1532.3,1544.5,1539.1
Utah,130.9,131.4,132.0,131.7,132.6,133.4,133.9,134.4,134.7,135.2,...,176.5,176.2,176.7,177.1,177.7,177.5,176.6,177.9,178.0,178.5
Virginia,380.0,380.1,378.5,382.3,384.8,386.5,390.0,391.9,394.6,394.6,...,422.6,420.6,419.9,421.1,421.3,420.1,419.7,419.5,419.9,417.9
Vermont,36.1,36.0,36.4,36.3,36.3,36.0,35.7,36.0,36.3,36.3,...,35.3,35.1,35.1,35.3,35.2,35.3,35.3,36.1,36.1,36.3
Washington,302.6,303.8,304.9,304.5,308.0,310.4,311.6,313.3,313.8,315.6,...,346.5,345.7,343.8,345.4,343.3,343.2,344.3,343.9,343.4,344.4
Wisconsin,267.6,267.4,268.8,269.2,270.3,270.4,270.3,270.8,272.0,273.5,...,290.9,289.6,290.2,290.3,288.3,288.2,287.3,289.3,290.0,289.8
West Virginia,74.5,74.4,73.9,74.4,74.5,74.4,74.6,74.5,74.9,74.7,...,71.9,71.8,72.4,72.7,72.5,71.6,71.7,71.6,71.1,70.7
Wyoming,36.1,36.2,36.2,36.4,36.2,36.3,36.2,36.0,36.4,36.0,...,38.7,38.1,38.1,38.2,38.1,38.2,37.9,38.4,38.6,38.5

us_manufacturing

,1990-01-01,1990-02-01,1990-03-01,1990-04-01,1990-05-01,1990-06-01,1990-07-01,1990-08-01,1990-09-01,1990-10-01,...,2025-05-01,2025-06-01,2025-07-01,2025-08-01,2025-09-01,2025-10-01,2025-11-01,2025-12-01,2026-01-01,2026-02-01
Alaska,12.4,12.4,12.9,13.7,14.5,14.5,14.3,14.4,14.0,14.0,...,12.5,12.5,12.4,12.4,12.1,12.9,12.3,12.7,12.5,12.6
Arkansas,218.4,218.9,217.8,219.0,219.2,219.9,219.8,220.2,221.1,220.0,...,159.9,159.4,158.9,158.6,158.2,158.7,158.8,158.5,159.0,158.7
Arizona,177.3,177.6,177.1,176.5,176.7,176.8,177.2,176.8,176.1,175.8,...,193.4,192.9,192.5,192.8,192.5,192.6,192.7,191.9,192.8,193.1
California,1985.5,1985.4,1982.7,1983.1,1980.3,1974.6,1970.3,1964.0,1953.3,1951.5,...,1221.9,1218.3,1214.4,1213.9,1210.5,1214.4,1212.2,1213.1,1214.3,1211.9
Colorado,169.7,170.0,170.3,171.1,170.4,170.3,170.4,169.9,169.7,170.0,...,146.4,145.7,145.8,146.0,145.8,146.3,145.5,145.4,144.3,143.7
Connecticut,305.1,304.8,304.5,304.8,302.9,301.4,301.5,297.5,295.4,292.5,...,150.1,152.7,152.1,152.1,152.1,151.5,151.8,151.2,152.2,152.6
Delaware,42.6,46.7,46.9,46.7,46.7,46.8,44.0,47.4,47.3,46.9,...,26.9,26.9,27.0,26.8,26.7,26.4,26.2,26.5,26.3,26.4
Florida,521.3,519.9,517.8,513.4,513.2,511.9,508.9,506.7,504.4,500.0,...,428.1,427.4,426.2,426.8,426.8,425.8,424.2,424.9,428.7,428.5
Georgia,524.9,526.9,528.2,529.4,527.5,527.5,521.0,519.7,517.0,513.9,...,429.6,427.9,424.4,426.2,425.0,425.6,424.3,427.0,425.7,425.5
Hawaii,21.0,21.0,21.0,20.6,20.4,20.4,20.4,20.4,20.5,20.4,...,13.0,13.0,13.0,13.0,13.0,13.0,13.0,13.0,13.1,13.1
Iowa,221.1,220.6,217.7,218.2,218.8,218.8,219.1,218.7,220.3,219.8,...,217.9,217.1,215.0,214.8,214.1,215.1,215.5,214.1,215.1,214.6
Idaho,51.4,52.6,53.0,52.9,52.9,52.8,52.0,52.4,53.9,53.2,...,75.6,75.2,75.1,75.0,74.9,75.8,75.9,75.7,76.0,75.2
Illinois,923.7,927.3,927.2,923.2,924.1,922.6,918.1,918.4,912.8,908.7,...,569.2,569.0,568.9,568.2,566.2,564.8,563.9,562.5,569.2,568.1
Indiana,605.6,607.3,609.6,609.6,609.7,609.7,612.3,609.9,608.0,606.6,...,518.5,517.5,513.8,516.7,516.1,517.5,516.1,515.4,515.7,518.1
Kansas,175.2,177.5,178.4,178.5,178.7,179.4,178.5,176.3,178.3,177.7,...,174.2,172.4,172.5,172.5,172.3,172.7,172.8,172.4,172.8,173.0
Kentucky,271.2,272.9,274.3,273.4,274.0,274.1,274.3,273.8,273.3,272.5,...,253.8,252.9,252.3,251.8,251.3,251.0,251.2,250.9,252.0,251.4
Louisiana,173.2,174.0,174.4,175.1,175.3,176.7,177.1,178.3,179.2,177.9,...,140.5,140.4,140.5,140.6,140.3,141.9,141.7,141.9,141.4,141.9
Massachusetts,494.2,492.1,490.0,486.6,484.1,481.8,481.1,478.0,474.7,470.1,...,227.0,226.1,225.9,225.6,225.0,226.2,226.9,227.3,228.4,227.5
Maryland,201.8,204.7,204.3,203.3,203.3,203.3,202.4,201.1,200.2,197.9,...,111.1,111.1,110.1,109.5,109.6,110.0,110.2,110.1,110.7,111.1
Maine,95.0,94.9,94.9,94.5,94.1,94.1,92.9,92.9,92.3,91.1,...,51.4,51.3,51.3,51.1,51.1,51.2,51.2,51.3,51.4,51.6
Michigan,810.0,836.0,848.3,843.3,838.1,841.8,838.1,832.2,832.2,830.7,...,590.1,587.9,586.7,585.4,585.4,584.7,581.9,582.5,578.7,578.5
Minnesota,343.9,343.9,343.6,340.9,341.0,341.9,341.7,342.3,341.7,340.8,...,315.5,314.4,313.6,314.1,313.8,313.8,314.3,316.3,314.6,313.3
Missouri,395.1,396.0,394.3,395.6,395.2,396.3,392.8,393.6,391.7,390.0,...,283.2,282.8,282.9,279.4,278.9,276.4,277.3,277.9,277.9,280.2
Mississippi,225.4,226.7,228.0,229.0,230.1,231.3,231.3,231.4,231.3,231.6,...,138.6,138.5,138.8,138.7,138.5,138.7,138.7,138.6,137.8,138.2
Montana,19.3,19.2,19.3,19.5,19.5,19.4,19.7,19.6,19.3,19.7,...,21.2,21.2,21.1,21.0,20.9,20.6,20.5,20.5,20.7,20.7
North Carolina,834.0,839.3,838.7,837.8,831.6,828.2,823.6,820.1,818.2,809.9,...,461.8,460.4,459.2,458.9,457.3,456.3,454.3,453.2,451.1,450.0
North Dakota,14.9,15.2,15.4,15.1,15.5,15.6,15.5,15.6,15.6,15.9,...,27.9,27.8,27.7,27.7,27.6,27.8,27.9,28.0,28.0,28.1
Nebraska,95.8,95.9,96.0,96.8,96.6,97.6,97.7,98.2,98.0,98.1,...,103.1,102.8,102.2,102.3,101.9,101.4,101.7,102.4,102.5,98.6
New Hampshire,100.9,101.2,100.8,100.5,99.9,99.4,98.7,97.9,97.1,96.0,...,67.9,67.5,67.6,67.6,67.6,67.0,67.1,67.0,67.4,67.4
New Jersey,549.1,548.6,544.3,538.0,533.6,529.4,526.7,524.0,519.8,515.6,...,253.6,252.9,252.1,251.6,251.5,250.8,250.3,249.2,249.4,248.9
New Mexico,37.5,37.3,37.7,38.0,38.4,38.4,38.2,38.1,38.2,38.2,...,28.2,28.0,28.1,27.8,27.6,28.0,28.0,27.9,27.9,27.8
Nevada,23.5,23.8,24.2,24.2,24.3,24.1,23.9,24.1,24.3,24.8,...,67.7,68.0,68.4,68.3,68.5,68.4,68.3,68.3,68.1,68.1
New York,1009.7,1007.3,1005.4,995.8,994.6,989.3,982.2,972.6,969.9,962.7,...,406.5,405.1,404.3,403.9,403.2,398.4,398.8,399.5,399.5,397.2
Ohio,1044.4,1061.6,1064.6,1068.6,1068.6,1069.4,1068.2,1066.3,1064.8,1059.3,...,678.4,677.3,675.5,675.8,674.3,678.2,679.4,679.3,677.7,678.1
Oklahoma,158.5,159.9,161.2,161.9,162.4,162.9,162.9,160.2,162.9,162.6,...,140.9,140.6,140.2,140.1,139.9,140.4,140.5,138.9,139.3,138.9
Oregon,206.2,205.2,205.7,205.4,205.5,204.9,204.7,206.8,203.4,200.7,...,180.3,179.5,179.2,178.3,177.1,177.6,177.5,178.8,177.2,177.0
Pennsylvania,965.4,964.5,962.5,958.4,957.1,954.5,951.2,948.9,945.8,941.0,...,558.4,556.9,556.1,555.1,553.9,553.4,552.3,552.4,554.4,551.8
Rhode Island,97.5,97.1,96.9,95.7,94.9,95.2,94.9,94.8,94.3,94.1,...,39.3,39.3,39.2,39.1,39.2,39.0,39.1,39.1,39.1,39.2
South Carolina,353.4,353.4,352.3,352.2,351.4,350.7,348.5,346.5,345.0,343.1,...,263.0,262.1,261.8,262.2,262.2,262.9,262.3,261.9,261.6,264.2
South Dakota,32.5,32.8,33.1,32.8,33.4,33.6,34.2,34.0,34.1,33.8,...,44.5,44.1,44.1,44.2,44.1,44.1,43.9,43.5,43.9,43.9
District of Columbia,7.6,7.6,7.5,7.4,7.3,7.2,7.3,7.2,7.2,7.1,...,1.1,1.1,1.1,1.1,1.1,1.0,1.0,1.0,1.0,1.0
Alabama,365.5,362.5,360.6,366.6,366.2,367.5,364.6,364.7,364.9,363.4,...,284.6,283.7,283.1,282.8,282.3,283.4,284.1,283.1,283.2,283.5
Tennessee,502.7,503.8,504.0,503.9,504.7,502.0,498.5,496.7,497.0,495.3,...,356.9,356.0,354.6,354.4,353.1,353.3,352.8,352.0,351.9,351.9
Texas,938.8,939.4,940.8,942.2,940.7,941.8,947.2,950.2,949.6,950.7,...,987.9,986.3,985.5,983.7,982.2,981.0,980.1,981.1,977.0,979.5
Utah,101.6,101.9,101.9,104.1,104.1,104.9,104.6,105.2,105.1,104.6,...,154.5,154.1,154.0,153.8,154.0,154.3,153.6,154.3,154.4,153.6
Virginia,391.3,391.0,391.6,390.6,389.1,389.3,388.9,387.4,386.1,383.6,...,240.0,238.0,237.2,235.3,234.5,233.3,232.8,232.3,230.2,228.6
Vermont,44.2,43.7,43.4,43.0,43.2,43.1,42.7,42.7,42.2,42.0,...,27.6,27.3,27.4,27.4,27.4,27.3,27.3,27.4,27.5,27.4
Washington,337.7,337.4,338.6,337.2,336.4,336.7,337.3,336.1,335.8,333.5,...,271.5,271.0,270.5,269.3,268.6,269.6,267.9,269.7,271.0,271.1
Wisconsin,524.5,527.9,526.8,525.1,525.3,525.5,523.5,524.4,523.8,524.0,...,459.4,458.6,458.5,457.2,456.2,455.7,454.8,454.6,451.6,451.5
West Virginia,81.9,82.1,82.5,82.7,82.7,83.1,82.6,82.6,82.1,82.0,...,45.4,45.2,45.2,45.1,45.0,45.0,44.9,45.0,44.9,44.9
Wyoming,8.9,8.8,9.1,9.0,9.1,9.1,9.3,9.1,9.3,9.3,...,10.4,10.4,10.5,10.6,10.4,10.4,10.4,10.4,10.4,10.3

### Saving to CSV

In [ ]:
for name, df in dfs.items():
    df.to_csv(f'../Cleaned Files/{name}.csv')