In [ ]:
import pandas as pd

In [ ]:
url = 'C:/GitHub/BIA-Team-Bravo/Data/raw/Canada Debt.csv'
df = pd.read_csv(url)

In [9]:
df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Estimates', 'UOM', 'UOM_ID',
       'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 'STATUS',
       'SYMBOL', 'TERMINATED', 'DECIMALS'],
      dtype='str')

In [10]:
df

,REF_DATE,GEO,DGUID,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2015,Canada,2016A000011124,Household income,Dollars,81,millions,6,v62790675,1.10,1689159.00,NaN,NaN,NaN,0
1,2016,Canada,2016A000011124,Household income,Dollars,81,millions,6,v62790675,1.10,1704299.00,NaN,NaN,NaN,0
2,2017,Canada,2016A000011124,Household income,Dollars,81,millions,6,v62790675,1.10,1779954.00,NaN,NaN,NaN,0
3,2018,Canada,2016A000011124,Household income,Dollars,81,millions,6,v62790675,1.10,1854265.00,NaN,NaN,NaN,0
4,2019,Canada,2016A000011124,Household income,Dollars,81,millions,6,v62790675,1.10,1940290.00,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1535,2020,British Columbia,2016A000259,"Equals: debt service ratio, interest only",Ratio,272,units,0,v62790828,11.14,7.22,NaN,NaN,NaN,2
1536,2021,British Columbia,2016A000259,"Equals: debt service ratio, interest only",Ratio,272,units,0,v62790828,11.14,6.63,NaN,NaN,NaN,2
1537,2022,British Columbia,2016A000259,"Equals: debt service ratio, interest only",Ratio,272,units,0,v62790828,11.14,7.82,NaN,NaN,NaN,2
1538,2023,British Columbia,2016A000259,"Equals: debt service ratio, interest only",Ratio,272,units,0,v62790828,11.14,10.06,NaN,NaN,NaN,2
1539,2024,British Columbia,2016A000259,"Equals: debt service ratio, interest only",Ratio,272,units,0,v62790828,11.14,10.28,NaN,NaN,NaN,2

In [22]:
ef = df[['GEO', 'Estimates', 'VALUE']]

In [27]:
ef[ef['Estimates'] == 'Equals: debt service ratio, interest only']

                       GEO                                  Estimates  VALUE
REF_DATE
2015                Canada  Equals: debt service ratio, interest only   6.41
2016                Canada  Equals: debt service ratio, interest only   6.47
2017                Canada  Equals: debt service ratio, interest only   6.48
2018                Canada  Equals: debt service ratio, interest only   7.06
2019                Canada  Equals: debt service ratio, interest only   7.43
...                    ...                                        ...    ...
2020      British Columbia  Equals: debt service ratio, interest only   7.22
2021      British Columbia  Equals: debt service ratio, interest only   6.63
2022      British Columbia  Equals: debt service ratio, interest only   7.82
2023      British Columbia  Equals: debt service ratio, interest only  10.06
2024      British Columbia  Equals: debt service ratio, interest only  10.28

[110 rows x 3 columns]

In [ ]:
ef.to_csv('C:\GitHub\BIA-Team-Bravo\Data\Clean\Canada Debt')