In [1]:
import pandas as pd
import plotly.express as px

In [2]:
url = "C:\GitHub\BIA-Team-Bravo\data\clean\Cleaned Employment by industry.csv"
df = pd.read_csv(url)

In [11]:
df

,REF_DATE,GEO,North American Industry Classification System (NAICS),Statistics,VALUE
0,2015-01-01,Canada,"Total employed, all industries",Estimate,17813.1
2,2015-01-01,Canada,"Total employed, all industries",Estimate,17466.0
4,2015-02-01,Canada,"Total employed, all industries",Estimate,17826.3
6,2015-03-01,Canada,"Total employed, all industries",Estimate,17854.1
8,2015-03-01,Canada,"Total employed, all industries",Estimate,17551.6
...,...,...,...,...,...
65196,2026-01-01,Canada,Goods-producing sector,Estimate,4224.4
65198,2026-01-01,Canada,Goods-producing sector,Estimate,4067.4
65200,2026-02-01,Canada,Goods-producing sector,Estimate,4214.7
65202,2026-03-01,Canada,Goods-producing sector,Estimate,4209.0
65204,2026-03-01,Canada,Goods-producing sector,Estimate,4082.9

In [12]:
df.describe()

              VALUE
count  32590.000000
mean     627.127079
std     2083.645297
min        0.200000
25%       21.600000
50%       80.500000
75%      376.900000
max    21206.700000

In [19]:
#Values for different industries in Nova Scotia
df[(df['GEO']=='Nova Scotia') & (df['North American Industry Classification System (NAICS)'] != 'North American Industry Classification System (NAICS)')].describe()

             VALUE
count  2835.000000
mean     71.454780
std     119.785362
min       2.500000
25%      17.500000
50%      29.700000
75%      65.750000
max     535.900000

In [5]:
fig = px.line(
    df[
        (df['North American Industry Classification System (NAICS)'] == 'Goods-producing sector') &
        (df['GEO'] != 'Canada')
    ],
    x='REF_DATE',
    y='VALUE',
    color = 'GEO',
    title = 'Goods-Producing Labour Force',
    labels={
                     "VALUE": "Workforce X 1000",
                     "GEO": "Province",
                     "REF_DATE": "Date"
                 },
)
fig.show()

In [6]:
fig = px.line(
    df[
        (df['North American Industry Classification System (NAICS)'] == 'Goods-producing sector') &
        (df['GEO'] == 'Nova Scotia')
    ],
    x='REF_DATE',
    y='VALUE',
    title = 'Nova Scotia Goods-Producing Labour Force',
    labels={
                     "VALUE": "Workforce X 1000",
                     "GEO": "Province",
                     "REF_DATE": "Date"
                 },
)
fig.show()

In [10]:
df = df[df.index%2==0]
fig = px.bar(df[(df['GEO'] == 'Nova Scotia') & (df['REF_DATE'] == '2026-03-01')], 
x='North American Industry Classification System (NAICS)', 
y='VALUE',
labels={
                     "VALUE": "Workforce X 1000",
                     'North American Industry Classification System (NAICS)':'Industry'
                 },
title = 'Nova Scotia Workforce March 2026' 
)
fig.show()

In [42]:
df[(df['GEO'] == 'Nova Scotia') & (df['REF_DATE'] == '2026-03-01')]

,REF_DATE,GEO,North American Industry Classification System (NAICS),Statistics,VALUE
1213,2026-03-01,Nova Scotia,"Total employed, all industries",Estimate,528.0
1214,2026-03-01,Nova Scotia,"Total employed, all industries",Estimate,524.1
5263,2026-03-01,Nova Scotia,Goods-producing sector,Estimate,97.4
5264,2026-03-01,Nova Scotia,Goods-producing sector,Estimate,94.1
41713,2026-03-01,Nova Scotia,Public administration [91],Estimate,39.1
41714,2026-03-01,Nova Scotia,Public administration [91],Estimate,39.2
41983,2026-03-01,Nova Scotia,Other services (except public administration) ...,Estimate,20.6
41984,2026-03-01,Nova Scotia,Other services (except public administration) ...,Estimate,20.7
42253,2026-03-01,Nova Scotia,Accommodation and food services [72],Estimate,30.7
42254,2026-03-01,Nova Scotia,Accommodation and food services [72],Estimate,30.3
42523,2026-03-01,Nova Scotia,"Information, culture and recreation [51, 71]",Estimate,20.2
42524,2026-03-01,Nova Scotia,"Information, culture and recreation [51, 71]",Estimate,18.6
42793,2026-03-01,Nova Scotia,Health care and social assistance [62],Estimate,87.5
42794,2026-03-01,Nova Scotia,Health care and social assistance [62],Estimate,87.2
43063,2026-03-01,Nova Scotia,Educational services [61],Estimate,43.1
43064,2026-03-01,Nova Scotia,Educational services [61],Estimate,44.4
43333,2026-03-01,Nova Scotia,"Business, building and other support services ...",Estimate,16.8
43334,2026-03-01,Nova Scotia,"Business, building and other support services ...",Estimate,16.7
43603,2026-03-01,Nova Scotia,"Professional, scientific and technical service...",Estimate,39.7
43604,2026-03-01,Nova Scotia,"Professional, scientific and technical service...",Estimate,39.7
43873,2026-03-01,Nova Scotia,"Finance, insurance, real estate, rental and le...",Estimate,29.6
43874,2026-03-01,Nova Scotia,"Finance, insurance, real estate, rental and le...",Estimate,29.9
44143,2026-03-01,Nova Scotia,Transportation and warehousing [48-49],Estimate,27.6
44144,2026-03-01,Nova Scotia,Transportation and warehousing [48-49],Estimate,28.5
44413,2026-03-01,Nova Scotia,Retail trade [44-45],Estimate,60.8
44414,2026-03-01,Nova Scotia,Retail trade [44-45],Estimate,60.0
44683,2026-03-01,Nova Scotia,Wholesale trade [41],Estimate,14.8
44684,2026-03-01,Nova Scotia,Wholesale trade [41],Estimate,14.8
44953,2026-03-01,Nova Scotia,"Wholesale and retail trade [41, 44-45]",Estimate,75.6
44954,2026-03-01,Nova Scotia,"Wholesale and retail trade [41, 44-45]",Estimate,74.9
45223,2026-03-01,Nova Scotia,Services-producing sector,Estimate,430.6
45224,2026-03-01,Nova Scotia,Services-producing sector,Estimate,430.1
45493,2026-03-01,Nova Scotia,Manufacturing [31-33],Estimate,33.0
45494,2026-03-01,Nova Scotia,Manufacturing [31-33],Estimate,32.6
45763,2026-03-01,Nova Scotia,Construction [23],Estimate,44.5
45764,2026-03-01,Nova Scotia,Construction [23],Estimate,42.0
46033,2026-03-01,Nova Scotia,Utilities [22],Estimate,4.6
46034,2026-03-01,Nova Scotia,Utilities [22],Estimate,4.6
46303,2026-03-01,Nova Scotia,"Forestry, fishing, mining, quarrying, oil and ...",Estimate,11.7
46304,2026-03-01,Nova Scotia,"Forestry, fishing, mining, quarrying, oil and ...",Estimate,11.6
46573,2026-03-01,Nova Scotia,"Agriculture [111-112, 1100, 1151-1152]",Estimate,3.6
46574,2026-03-01,Nova Scotia,"Agriculture [111-112, 1100, 1151-1152]",Estimate,3.3

In [50]:
df[df.index%2==0]

,REF_DATE,GEO,North American Industry Classification System (NAICS),Statistics,VALUE
0,2015-01-01,Canada,"Total employed, all industries",Estimate,17813.1
2,2015-01-01,Canada,"Total employed, all industries",Estimate,17466.0
4,2015-02-01,Canada,"Total employed, all industries",Estimate,17826.3
6,2015-03-01,Canada,"Total employed, all industries",Estimate,17854.1
8,2015-03-01,Canada,"Total employed, all industries",Estimate,17551.6
...,...,...,...,...,...
65196,2026-01-01,Canada,Goods-producing sector,Estimate,4224.4
65198,2026-01-01,Canada,Goods-producing sector,Estimate,4067.4
65200,2026-02-01,Canada,Goods-producing sector,Estimate,4214.7
65202,2026-03-01,Canada,Goods-producing sector,Estimate,4209.0
65204,2026-03-01,Canada,Goods-producing sector,Estimate,4082.9