In [1]:
import pandas as pd

### Reading in CSVs
Creating Dataframes and a dictionary for use in the transformation

In [2]:
url_GDP_Income = '../data/raw/US GDP and Personal Income.csv'
url_US_Total_Employment = '../data/raw/US Total employment By States.csv'

In [3]:
US_GDP_Income = pd.read_csv(url_GDP_Income, skiprows=3, skipfooter=6, engine='python')
US_Total_Employment = pd.read_csv(url_US_Total_Employment, index_col=1, skipfooter=4, engine='python')

### Cleaning Up and Melting

US GDP and Personal Income

In [4]:
US_GDP_Income = US_GDP_Income.iloc[0:156]
US_GDP_Income['GeoName'] = US_GDP_Income['GeoName'].replace('Alaska *', 'Alaska')
US_GDP_Income = US_GDP_Income.melt(id_vars=['GeoFIPS', 'GeoName', 'LineCode', 'Description'])
US_GDP_Income.rename(columns={'variable':'Year_Quarter','GeoName':'State'}, inplace=True)
US_GDP_Income[['Year', 'Quarter']] = US_GDP_Income['Year_Quarter'].str.split(':', expand=True)
US_GDP_Income.drop(columns='Year_Quarter', inplace=True)

US Total employment By States

In [5]:
US_Total_Employment.drop(columns = ['2025'], inplace=True)
US_Total_Employment = US_Total_Employment.melt(id_vars=['GeoFIPS'],ignore_index=False)
US_Total_Employment.reset_index(inplace=True)
US_Total_Employment.rename(columns = {'GeoName':'State','variable':'Year'}, inplace=True)

In [6]:
#Final Checking
display(US_GDP_Income)
display(US_Total_Employment)

,GeoFIPS,State,LineCode,Description,value,Year,Quarter
0,0,United States,1,"Personal income (millions of dollars, seasonal...",15276302.2,2015,Q1
1,0,United States,2,"Population (midperiod, persons) 1",320914934.0,2015,Q1
2,0,United States,3,Per capita personal income (dollars) 2,47602.0,2015,Q1
3,1000,Alabama,1,"Personal income (millions of dollars, seasonal...",185291.7,2015,Q1
4,1000,Alabama,2,"Population (midperiod, persons) 1",4902063.0,2015,Q1
...,...,...,...,...,...,...,...
6859,55000,Wisconsin,2,"Population (midperiod, persons) 1",5977495.0,2025,Q4
6860,55000,Wisconsin,3,Per capita personal income (dollars) 2,71338.0,2025,Q4
6861,56000,Wyoming,1,"Personal income (millions of dollars, seasonal...",53368.3,2025,Q4
6862,56000,Wyoming,2,"Population (midperiod, persons) 1",589456.0,2025,Q4
6863,56000,Wyoming,3,Per capita personal income (dollars) 2,90538.0,2025,Q4

             State  GeoFIPS  Year      value
0    United States        0  2015  190325800
1          Alabama     1000  2015    2587641
2           Alaska     2000  2015     461707
3          Arizona     4000  2015    3547647
4         Arkansas     5000  2015    1610799
..             ...      ...   ...        ...
515       Virginia    51000  2024    5773598
516     Washington    53000  2024    4904120
517  West Virginia    54000  2024     914033
518      Wisconsin    55000  2024    3867941
519        Wyoming    56000  2024     447255

[520 rows x 4 columns]

### Saving to CSV

In [7]:
US_Total_Employment.to_csv('../data/clean/US_Total_Employment.csv')
US_GDP_Income.to_csv('../data/clean/US_GDP_Income.csv')