In [24]:
import pandas as pd
import plotly.express as px

In [25]:
url = '../data/clean/NS minimum wage.csv'
df = pd.read_csv(url, index_col=0)
df = df[df['Experience Level'] != 'Experienced']

In [26]:
df

   Effective Date  Minimum Wage Rate Experience Level
0      2026-04-01              16.75   Not Applicable
1      2025-10-01              16.50   Not Applicable
2      2025-04-01              15.70   Not Applicable
3      2024-04-01              15.20   Not Applicable
4      2023-10-01              15.00   Not Applicable
5      2023-04-01              14.50   Not Applicable
6      2022-10-01              13.60   Not Applicable
7      2022-04-01              13.35   Not Applicable
8      2021-04-01              12.95   Not Applicable
9      2020-04-01              12.55   Not Applicable
11     2019-04-01              11.05    Inexperienced
13     2018-04-01              10.50    Inexperienced
15     2017-04-01              10.35    Inexperienced
17     2016-04-01              10.20    Inexperienced

In [27]:
px.line(df,x = 'Effective Date', y = 'Minimum Wage Rate')

In [28]:
url2 = '../data/clean/Cleaned Employment, average hourly and weekly earnings (including overtime),.csv'
df2 = pd.read_csv(url2)
df2 = df2[(df2['GEO']== 'Nova Scotia')]
df2

,REF_DATE,GEO,Estimate,UOM,VALUE
399,2015-01-01,Nova Scotia,Average weekly earnings including overtime for...,Dollars,836.28
400,2015-02-01,Nova Scotia,Average weekly earnings including overtime for...,Dollars,825.99
401,2015-03-01,Nova Scotia,Average weekly earnings including overtime for...,Dollars,821.28
402,2015-04-01,Nova Scotia,Average weekly earnings including overtime for...,Dollars,836.09
403,2015-05-01,Nova Scotia,Average weekly earnings including overtime for...,Dollars,830.69
...,...,...,...,...,...
20078,2025-09-01,Nova Scotia,Employment for all employees,Persons,457525.00
20079,2025-10-01,Nova Scotia,Employment for all employees,Persons,455884.00
20080,2025-11-01,Nova Scotia,Employment for all employees,Persons,457572.00
20081,2025-12-01,Nova Scotia,Employment for all employees,Persons,457776.00
20082,2026-01-01,Nova Scotia,Employment for all employees,Persons,456848.00

In [31]:
fig = px.line(
    df,
    x="Effective Date",
    y="Minimum Wage Rate",
    title="Minimum Wage vs Estimates",
    labels='Minimum Wage'
)

for estimate in df2["Estimate"].value_counts().index:
    df3 = df2[(df2["Estimate"] == 'Average hourly earnings including overtime for hourly employees') | 
       (df2['Estimate'] == 'Average hourly earnings including overtime for salaried employees')]
    subset = df3[df3["Estimate"] == estimate]

    fig.add_scatter(
        x=subset["REF_DATE"],
        y=subset["VALUE"],
        mode="lines",
        name=str(estimate)
    )

fig.show()

In [14]:
df2[(df2["Estimate"] == 'Average hourly earnings including overtime for hourly employees') | 
       (df2['Estimate'] == 'Average hourly earnings including overtime for salaried employees')]

,REF_DATE,GEO,Estimate,UOM,VALUE
6916,2015-01-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,21.57
6917,2015-02-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,21.35
6918,2015-03-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,21.23
6919,2015-04-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,21.99
6920,2015-05-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,21.17
...,...,...,...,...,...
7975,2025-09-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,44.53
7976,2025-10-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,44.99
7977,2025-11-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,44.46
7978,2025-12-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,44.33
7979,2026-01-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,44.54

In [17]:
df2

,REF_DATE,GEO,Estimate,UOM,VALUE
6916,2015-01-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,21.57
6917,2015-02-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,21.35
6918,2015-03-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,21.23
6919,2015-04-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,21.99
6920,2015-05-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,21.17
...,...,...,...,...,...
7975,2025-09-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,44.53
7976,2025-10-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,44.99
7977,2025-11-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,44.46
7978,2025-12-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,44.33
7979,2026-01-01,Nova Scotia,Average hourly earnings including overtime for...,Dollars,44.54