In [6]:
import pandas as pd
import plotly.express as px

In [23]:
url = '../data/clean/Cleaned Employment, average hourly and weekly earnings (including overtime),.csv'
df = pd.read_csv(url)
df = df[(df['GEO']!= 'Yukon') & (df['GEO']!='Northwest Territories') & (df['GEO']!='Nunavut')]
df

,REF_DATE,GEO,Estimate,UOM,VALUE
0,2015-01-01,Canada,Average weekly earnings including overtime for...,Dollars,948.50
1,2015-02-01,Canada,Average weekly earnings including overtime for...,Dollars,949.46
2,2015-03-01,Canada,Average weekly earnings including overtime for...,Dollars,951.71
3,2015-04-01,Canada,Average weekly earnings including overtime for...,Dollars,954.11
4,2015-05-01,Canada,Average weekly earnings including overtime for...,Dollars,948.27
...,...,...,...,...,...
20477,2025-09-01,Canada,Employment for all employees,Persons,17916693.00
20478,2025-10-01,Canada,Employment for all employees,Persons,17936493.00
20479,2025-11-01,Canada,Employment for all employees,Persons,17936847.00
20480,2025-12-01,Canada,Employment for all employees,Persons,17934011.00
20481,2026-01-01,Canada,Employment for all employees,Persons,17980391.00

In [25]:
for _ in df['Estimate'].value_counts().index[0:5]:
    fig = px.line(df[(df['Estimate'] == _)],x = 'REF_DATE', y = 'VALUE', color = 'GEO', title=_)
    fig.show()

In [36]:
for _ in df['Estimate'].value_counts().index[0:-3]:
    fig = px.line(df[(df['Estimate'] == _) & (df['GEO'] == 'Nova Scotia')],x = 'REF_DATE', y = 'VALUE', color = 'GEO', title=_)
    fig.show()

In [31]:
df[df['GEO'] == 'Nova Scotia']

,REF_DATE,GEO,Estimate,UOM,VALUE
399,2015-01-01,Nova Scotia,Average weekly earnings including overtime for...,Dollars,836.28
400,2015-02-01,Nova Scotia,Average weekly earnings including overtime for...,Dollars,825.99
401,2015-03-01,Nova Scotia,Average weekly earnings including overtime for...,Dollars,821.28
402,2015-04-01,Nova Scotia,Average weekly earnings including overtime for...,Dollars,836.09
403,2015-05-01,Nova Scotia,Average weekly earnings including overtime for...,Dollars,830.69
...,...,...,...,...,...
20078,2025-09-01,Nova Scotia,Employment for all employees,Persons,457525.00
20079,2025-10-01,Nova Scotia,Employment for all employees,Persons,455884.00
20080,2025-11-01,Nova Scotia,Employment for all employees,Persons,457572.00
20081,2025-12-01,Nova Scotia,Employment for all employees,Persons,457776.00
20082,2026-01-01,Nova Scotia,Employment for all employees,Persons,456848.00