In [2]:
import pandas as pd
import plotly.express as px

In [3]:
url = '../data/clean/Cleaned Employment by industry.csv'
df = pd.read_csv(url)
df = df[df['Data type'] == 'Seasonally adjusted']
df = df[df['Data type'] == 'Seasonally adjusted']
df

,REF_DATE,GEO,North American Industry Classification System,Statistics,Data type,VALUE
0,2015-01-01,Canada,"Total employed, all industries",Estimate,Seasonally adjusted,17813.1
1,2015-02-01,Canada,"Total employed, all industries",Estimate,Seasonally adjusted,17827.2
2,2015-03-01,Canada,"Total employed, all industries",Estimate,Seasonally adjusted,17854.1
3,2015-04-01,Canada,"Total employed, all industries",Estimate,Seasonally adjusted,17819.4
4,2015-05-01,Canada,"Total employed, all industries",Estimate,Seasonally adjusted,17843.7
...,...,...,...,...,...,...
31180,2025-11-01,British Columbia,"Total employed, all industries",Estimate,Seasonally adjusted,2949.5
31181,2025-12-01,British Columbia,"Total employed, all industries",Estimate,Seasonally adjusted,2944.1
31182,2026-01-01,British Columbia,"Total employed, all industries",Estimate,Seasonally adjusted,2947.6
31183,2026-02-01,British Columbia,"Total employed, all industries",Estimate,Seasonally adjusted,2927.4
31184,2026-03-01,British Columbia,"Total employed, all industries",Estimate,Seasonally adjusted,2908.2

In [4]:
for province in df['GEO'].value_counts().index:
    fig = px.line(df[(df['GEO'] == province) & ((df['North American Industry Classification System'] != 'Total employed, all industries' ))],
                  x='REF_DATE',
                  y='VALUE', 
                  color = ('North American Industry Classification System'), 
                  title= f'{province} Workforce Makeup')
    fig.show()

In [5]:
fig = px.line(df[(df['GEO'] != 'Canada') & (df['North American Industry Classification System'] == 'Services-producing sector')],
              x='REF_DATE',
              y='VALUE', 
              color = 'GEO', 
              title= f'Province Services Workforce Makeup')
fig.show()

In [ ]:
for province in df['GEO'].value_counts().index:
    fig = px.line(df[(df['GEO'] == province) & (df['North American Industry Classification System'] == 'Services-producing sector')],
                  x='REF_DATE',y='VALUE', 
                  title= f'{province} Services Workforce Makeup')
    fig.show()

In [ ]:
for province in df['GEO'].value_counts().index:
    fig = px.line(df[(df['GEO'] == province) & (df['North American Industry Classification System'] == 'Professional, scientific and technical services')],
                  x='REF_DATE',y='VALUE', 
                  title= f'{province} Professional Workforce Makeup')
    fig.show()

In [9]:
df

,REF_DATE,GEO,North American Industry Classification System,Statistics,Data type,VALUE
0,2015-01-01,Canada,"Total employed, all industries",Estimate,Seasonally adjusted,17813.1
1,2015-02-01,Canada,"Total employed, all industries",Estimate,Seasonally adjusted,17827.2
2,2015-03-01,Canada,"Total employed, all industries",Estimate,Seasonally adjusted,17854.1
3,2015-04-01,Canada,"Total employed, all industries",Estimate,Seasonally adjusted,17819.4
4,2015-05-01,Canada,"Total employed, all industries",Estimate,Seasonally adjusted,17843.7
...,...,...,...,...,...,...
31180,2025-11-01,British Columbia,"Total employed, all industries",Estimate,Seasonally adjusted,2949.5
31181,2025-12-01,British Columbia,"Total employed, all industries",Estimate,Seasonally adjusted,2944.1
31182,2026-01-01,British Columbia,"Total employed, all industries",Estimate,Seasonally adjusted,2947.6
31183,2026-02-01,British Columbia,"Total employed, all industries",Estimate,Seasonally adjusted,2927.4
31184,2026-03-01,British Columbia,"Total employed, all industries",Estimate,Seasonally adjusted,2908.2

In [10]:
df['North American Industry Classification System'].value_counts().index

Index(['Total employed, all industries', 'Goods-producing sector',
       'Agriculture', 'Forestry, fishing, mining, quarrying, oil and gas',
       'Utilities', 'Construction', 'Manufacturing',
       'Services-producing sector', 'Wholesale and retail trade',
       'Wholesale trade', 'Retail trade', 'Transportation and warehousing',
       'Finance, insurance, real estate, rental and leasing',
       'Professional, scientific and technical services',
       'Business, building and other support services', 'Educational services',
       'Health care and social assistance',
       'Information, culture and recreation',
       'Accommodation and food services',
       'Other services (except public administration)',
       'Public administration'],
      dtype='str', name='North American Industry Classification System')

In [3]:
df[(df['GEO'] == 'Canada') & (df['North American Industry Classification System'] != 'Total employed, all industries')]

,REF_DATE,GEO,North American Industry Classification System,Statistics,Data type,VALUE
135,2015-01-01,Canada,Goods-producing sector,Estimate,Seasonally adjusted,3900.0
136,2015-02-01,Canada,Goods-producing sector,Estimate,Seasonally adjusted,3881.4
137,2015-03-01,Canada,Goods-producing sector,Estimate,Seasonally adjusted,3877.4
138,2015-04-01,Canada,Goods-producing sector,Estimate,Seasonally adjusted,3870.2
139,2015-05-01,Canada,Goods-producing sector,Estimate,Seasonally adjusted,3875.1
...,...,...,...,...,...,...
2830,2025-11-01,Canada,Public administration,Estimate,Seasonally adjusted,1248.9
2831,2025-12-01,Canada,Public administration,Estimate,Seasonally adjusted,1255.0
2832,2026-01-01,Canada,Public administration,Estimate,Seasonally adjusted,1245.0
2833,2026-02-01,Canada,Public administration,Estimate,Seasonally adjusted,1253.1
2834,2026-03-01,Canada,Public administration,Estimate,Seasonally adjusted,1256.7

In [8]:
for province in df['GEO'].value_counts().index:
    print(df[(df['GEO'] == province) & (df['North American Industry Classification System'] != 'Total employed, all industries')])

        REF_DATE     GEO North American Industry Classification System  \
135   2015-01-01  Canada                        Goods-producing sector
136   2015-02-01  Canada                        Goods-producing sector
137   2015-03-01  Canada                        Goods-producing sector
138   2015-04-01  Canada                        Goods-producing sector
139   2015-05-01  Canada                        Goods-producing sector
...          ...     ...                                           ...
2830  2025-11-01  Canada                         Public administration
2831  2025-12-01  Canada                         Public administration
2832  2026-01-01  Canada                         Public administration
2833  2026-02-01  Canada                         Public administration
2834  2026-03-01  Canada                         Public administration

     Statistics            Data type   VALUE
135    Estimate  Seasonally adjusted  3900.0
136    Estimate  Seasonally adjusted  3881.4
137    Estimate  Seasonally adjusted  3877.4
138    Estimate  Seasonally adjusted  3870.2
139    Estimate  Seasonally adjusted  3875.1
...         ...                  ...     ...
2830   Estimate  Seasonally adjusted  1248.9
2831   Estimate  Seasonally adjusted  1255.0
2832   Estimate  Seasonally adjusted  1245.0
2833   Estimate  Seasonally adjusted  1253.1
2834   Estimate  Seasonally adjusted  1256.7

[2700 rows x 6 columns]
        REF_DATE                        GEO  \
2835  2015-01-01  Newfoundland and Labrador
2836  2015-02-01  Newfoundland and Labrador
2837  2015-03-01  Newfoundland and Labrador
2838  2015-04-01  Newfoundland and Labrador
2839  2015-05-01  Newfoundland and Labrador
...          ...                        ...
5530  2025-11-01  Newfoundland and Labrador
5531  2025-12-01  Newfoundland and Labrador
5532  2026-01-01  Newfoundland and Labrador
5533  2026-02-01  Newfoundland and Labrador
5534  2026-03-01  Newfoundland and Labrador

     North American Industry Classification System Statistics  \
2835                         Public administration   Estimate
2836                         Public administration   Estimate
2837                         Public administration   Estimate
2838                         Public administration   Estimate
2839                         Public administration   Estimate
...                                            ...        ...
5530                        Goods-producing sector   Estimate
5531                        Goods-producing sector   Estimate
5532                        Goods-producing sector   Estimate
5533                        Goods-producing sector   Estimate
5534                        Goods-producing sector   Estimate

                Data type  VALUE
2835  Seasonally adjusted   16.5
2836  Seasonally adjusted   16.3
2837  Seasonally adjusted   16.1
2838  Seasonally adjusted   15.9
2839  Seasonally adjusted   15.4
...                   ...    ...
5530  Seasonally adjusted   45.6
5531  Seasonally adjusted   45.9
5532  Seasonally adjusted   45.8
5533  Seasonally adjusted   47.6
5534  Seasonally adjusted   46.9

[2700 rows x 6 columns]
        REF_DATE                   GEO  \
5535  2015-01-01  Prince Edward Island
5536  2015-01-01  Prince Edward Island
5537  2015-01-01  Prince Edward Island
5538  2015-01-01  Prince Edward Island
5539  2015-01-01  Prince Edward Island
...          ...                   ...
8230  2025-08-01  Prince Edward Island
8231  2025-09-01  Prince Edward Island
8232  2025-09-01  Prince Edward Island
8233  2025-11-01  Prince Edward Island
8234  2026-01-01  Prince Edward Island

          North American Industry Classification System Statistics  \
5535                             Goods-producing sector   Estimate
5536                                        Agriculture   Estimate
5537  Forestry, fishing, mining, quarrying, oil and gas   Estimate
5538                                       Construction   Estimate
5539                                      Manufacturing   Estimate
...                                                 ...        ...
8230  Forestry, fishing, mining, quarrying, oil and gas   Estimate
8231                Information, culture and recreation   Estimate
8232      Other services (except public administration)   Estimate
8233      Other services (except public administration)   Estimate
8234                Information, culture and recreation   Estimate

                Data type  VALUE
5535  Seasonally adjusted   16.8
5536  Seasonally adjusted    2.9
5537  Seasonally adjusted    2.4
5538  Seasonally adjusted    5.5
5539  Seasonally adjusted    5.8
...                   ...    ...
8230  Seasonally adjusted    2.8
8231  Seasonally adjusted    2.8
8232  Seasonally adjusted    2.8
8233  Seasonally adjusted    2.8
8234  Seasonally adjusted    2.8

[2700 rows x 6 columns]
         REF_DATE          GEO North American Industry Classification System  \
8235   2015-01-01  Nova Scotia                         Public administration
8236   2015-02-01  Nova Scotia                         Public administration
8237   2015-03-01  Nova Scotia                         Public administration
8238   2015-04-01  Nova Scotia                         Public administration
8239   2015-05-01  Nova Scotia                         Public administration
...           ...          ...                                           ...
10930  2025-11-01  Nova Scotia                        Goods-producing sector
10931  2025-12-01  Nova Scotia                        Goods-producing sector
10932  2026-01-01  Nova Scotia                        Goods-producing sector
10933  2026-02-01  Nova Scotia                        Goods-producing sector
10934  2026-03-01  Nova Scotia                        Goods-producing sector

      Statistics            Data type  VALUE
8235    Estimate  Seasonally adjusted   24.4
8236    Estimate  Seasonally adjusted   25.0
8237    Estimate  Seasonally adjusted   25.5
8238    Estimate  Seasonally adjusted   24.7
8239    Estimate  Seasonally adjusted   24.4
...          ...                  ...    ...
10930   Estimate  Seasonally adjusted   97.1
10931   Estimate  Seasonally adjusted   98.2
10932   Estimate  Seasonally adjusted   99.3
10933   Estimate  Seasonally adjusted   97.6
10934   Estimate  Seasonally adjusted   97.4

[2700 rows x 6 columns]
         REF_DATE            GEO  \
10935  2015-01-01  New Brunswick
10936  2015-02-01  New Brunswick
10937  2015-03-01  New Brunswick
10938  2015-04-01  New Brunswick
10939  2015-05-01  New Brunswick
...           ...            ...
13630  2025-11-01  New Brunswick
13631  2025-12-01  New Brunswick
13632  2026-01-01  New Brunswick
13633  2026-02-01  New Brunswick
13634  2026-03-01  New Brunswick

      North American Industry Classification System Statistics  \
10935                        Goods-producing sector   Estimate
10936                        Goods-producing sector   Estimate
10937                        Goods-producing sector   Estimate
10938                        Goods-producing sector   Estimate
10939                        Goods-producing sector   Estimate
...                                             ...        ...
13630                         Public administration   Estimate
13631                         Public administration   Estimate
13632                         Public administration   Estimate
13633                         Public administration   Estimate
13634                         Public administration   Estimate

                 Data type  VALUE
10935  Seasonally adjusted   74.3
10936  Seasonally adjusted   75.5
10937  Seasonally adjusted   74.2
10938  Seasonally adjusted   74.5
10939  Seasonally adjusted   72.2
...                    ...    ...
13630  Seasonally adjusted   38.1
13631  Seasonally adjusted   38.9
13632  Seasonally adjusted   37.3
13633  Seasonally adjusted   37.9
13634  Seasonally adjusted   36.9

[2700 rows x 6 columns]
         REF_DATE     GEO North American Industry Classification System  \
13635  2015-01-01  Quebec                         Public administration
13636  2015-02-01  Quebec                         Public administration
13637  2015-03-01  Quebec                         Public administration
13638  2015-04-01  Quebec                         Public administration
13639  2015-05-01  Quebec                         Public administration
...           ...     ...                                           ...
16330  2025-11-01  Quebec                        Goods-producing sector
16331  2025-12-01  Quebec                        Goods-producing sector
16332  2026-01-01  Quebec                        Goods-producing sector
16333  2026-02-01  Quebec                        Goods-producing sector
16334  2026-03-01  Quebec                        Goods-producing sector

      Statistics            Data type  VALUE
13635   Estimate  Seasonally adjusted  221.4
13636   Estimate  Seasonally adjusted  221.7
13637   Estimate  Seasonally adjusted  220.3
13638   Estimate  Seasonally adjusted  220.8
13639   Estimate  Seasonally adjusted  218.2
...          ...                  ...    ...
16330   Estimate  Seasonally adjusted  961.2
16331   Estimate  Seasonally adjusted  964.4
16332   Estimate  Seasonally adjusted  965.2
16333   Estimate  Seasonally adjusted  953.4
16334   Estimate  Seasonally adjusted  943.7

[2700 rows x 6 columns]
         REF_DATE      GEO North American Industry Classification System  \
16335  2015-01-01  Ontario                        Goods-producing sector
16336  2015-02-01  Ontario                        Goods-producing sector
16337  2015-03-01  Ontario                        Goods-producing sector
16338  2015-04-01  Ontario                        Goods-producing sector
16339  2015-05-01  Ontario                        Goods-producing sector
...           ...      ...                                           ...
19030  2025-11-01  Ontario                         Public administration
19031  2025-12-01  Ontario                         Public administration
19032  2026-01-01  Ontario                         Public administration
19033  2026-02-01  Ontario                         Public administration
19034  2026-03-01  Ontario                         Public administration

      Statistics            Data type   VALUE
16335   Estimate  Seasonally adjusted  1380.9
16336   Estimate  Seasonally adjusted  1385.3
16337   Estimate  Seasonally adjusted  1380.9
16338   Estimate  Seasonally adjusted  1386.8
16339   Estimate  Seasonally adjusted  1405.8
...          ...                  ...     ...
19030   Estimate  Seasonally adjusted   467.3
19031   Estimate  Seasonally adjusted   469.1
19032   Estimate  Seasonally adjusted   467.0
19033   Estimate  Seasonally adjusted   474.0
19034   Estimate  Seasonally adjusted   470.3

[2700 rows x 6 columns]
         REF_DATE       GEO North American Industry Classification System  \
19035  2015-01-01  Manitoba                         Public administration
19036  2015-02-01  Manitoba                         Public administration
19037  2015-03-01  Manitoba                         Public administration
19038  2015-04-01  Manitoba                         Public administration
19039  2015-05-01  Manitoba                         Public administration
...           ...       ...                                           ...
21730  2025-11-01  Manitoba                        Goods-producing sector
21731  2025-12-01  Manitoba                        Goods-producing sector
21732  2026-01-01  Manitoba                        Goods-producing sector
21733  2026-02-01  Manitoba                        Goods-producing sector
21734  2026-03-01  Manitoba                        Goods-producing sector

      Statistics            Data type  VALUE
19035   Estimate  Seasonally adjusted   32.8
19036   Estimate  Seasonally adjusted   32.6
19037   Estimate  Seasonally adjusted   32.0
19038   Estimate  Seasonally adjusted   32.7
19039   Estimate  Seasonally adjusted   33.5
...          ...                  ...    ...
21730   Estimate  Seasonally adjusted  156.9
21731   Estimate  Seasonally adjusted  158.0
21732   Estimate  Seasonally adjusted  158.1
21733   Estimate  Seasonally adjusted  160.4
21734   Estimate  Seasonally adjusted  167.5

[2700 rows x 6 columns]
         REF_DATE           GEO North American Industry Classification System  \
21735  2015-01-01  Saskatchewan                        Goods-producing sector
21736  2015-02-01  Saskatchewan                        Goods-producing sector
21737  2015-03-01  Saskatchewan                        Goods-producing sector
21738  2015-04-01  Saskatchewan                        Goods-producing sector
21739  2015-05-01  Saskatchewan                        Goods-producing sector
...           ...           ...                                           ...
24430  2025-11-01  Saskatchewan                         Public administration
24431  2025-12-01  Saskatchewan                         Public administration
24432  2026-01-01  Saskatchewan                         Public administration
24433  2026-02-01  Saskatchewan                         Public administration
24434  2026-03-01  Saskatchewan                         Public administration

      Statistics            Data type  VALUE
21735   Estimate  Seasonally adjusted  158.9
21736   Estimate  Seasonally adjusted  157.0
21737   Estimate  Seasonally adjusted  158.6
21738   Estimate  Seasonally adjusted  160.6
21739   Estimate  Seasonally adjusted  158.9
...          ...                  ...    ...
24430   Estimate  Seasonally adjusted   41.4
24431   Estimate  Seasonally adjusted   42.0
24432   Estimate  Seasonally adjusted   41.5
24433   Estimate  Seasonally adjusted   41.3
24434   Estimate  Seasonally adjusted   40.7

[2700 rows x 6 columns]
         REF_DATE      GEO North American Industry Classification System  \
24435  2015-01-01  Alberta                         Public administration
24436  2015-02-01  Alberta                         Public administration
24437  2015-03-01  Alberta                         Public administration
24438  2015-04-01  Alberta                         Public administration
24439  2015-05-01  Alberta                         Public administration
...           ...      ...                                           ...
27130  2025-11-01  Alberta                        Goods-producing sector
27131  2025-12-01  Alberta                        Goods-producing sector
27132  2026-01-01  Alberta                        Goods-producing sector
27133  2026-02-01  Alberta                        Goods-producing sector
27134  2026-03-01  Alberta                        Goods-producing sector

      Statistics            Data type  VALUE
24435   Estimate  Seasonally adjusted   87.8
24436   Estimate  Seasonally adjusted   90.7
24437   Estimate  Seasonally adjusted   94.6
24438   Estimate  Seasonally adjusted   95.1
24439   Estimate  Seasonally adjusted   91.7
...          ...                  ...    ...
27130   Estimate  Seasonally adjusted  614.6
27131   Estimate  Seasonally adjusted  610.5
27132   Estimate  Seasonally adjusted  621.5
27133   Estimate  Seasonally adjusted  620.4
27134   Estimate  Seasonally adjusted  624.1

[2700 rows x 6 columns]
         REF_DATE               GEO  \
27135  2015-01-01  British Columbia
27136  2015-02-01  British Columbia
27137  2015-03-01  British Columbia
27138  2015-04-01  British Columbia
27139  2015-05-01  British Columbia
...           ...               ...
29830  2025-11-01  British Columbia
29831  2025-12-01  British Columbia
29832  2026-01-01  British Columbia
29833  2026-02-01  British Columbia
29834  2026-03-01  British Columbia

      North American Industry Classification System Statistics  \
27135                        Goods-producing sector   Estimate
27136                        Goods-producing sector   Estimate
27137                        Goods-producing sector   Estimate
27138                        Goods-producing sector   Estimate
27139                        Goods-producing sector   Estimate
...                                             ...        ...
29830                         Public administration   Estimate
29831                         Public administration   Estimate
29832                         Public administration   Estimate
29833                         Public administration   Estimate
29834                         Public administration   Estimate

                 Data type  VALUE
27135  Seasonally adjusted  479.1
27136  Seasonally adjusted  476.4
27137  Seasonally adjusted  483.7
27138  Seasonally adjusted  473.6
27139  Seasonally adjusted  474.2
...                    ...    ...
29830  Seasonally adjusted  159.1
29831  Seasonally adjusted  159.5
29832  Seasonally adjusted  156.4
29833  Seasonally adjusted  156.3
29834  Seasonally adjusted  156.5

[2700 rows x 6 columns]